'use client';

import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Phone,
  Mail,
  Users,
  FileText,
  RefreshCw,
  File,
  Bot,
  Plus,
  Filter,
  Calendar,
  Clock,
  User
} from 'lucide-react';
import { ActivityType, Activity, CreateActivityInput } from '@/lib/activity-api';

interface TimelineItem {
  id: string;
  type: ActivityType;
  subject: string;
  content?: string;
  date: string;
  user: { id: string; name: string };
  isAutoGenerated: boolean;
  metadata?: Record<string, any>;
}

interface ActivityTimelineProps {
  entityType: string;
  entityId: string;
  timeline: TimelineItem[];
  onActivityAdd?: (activity: CreateActivityInput) => void;
  showForm?: boolean;
  isLoading?: boolean;
}

// 활동 유형별 아이콘 및 색상
const activityConfig: Record<ActivityType, { icon: React.ElementType; color: string; label: string }> = {
  CALL: { icon: Phone, color: 'text-green-500 bg-green-50', label: '전화' },
  EMAIL: { icon: Mail, color: 'text-blue-500 bg-blue-50', label: '이메일' },
  MEETING: { icon: Users, color: 'text-purple-500 bg-purple-50', label: '미팅' },
  NOTE: { icon: FileText, color: 'text-yellow-500 bg-yellow-50', label: '메모' },
  TASK: { icon: FileText, color: 'text-orange-500 bg-orange-50', label: '태스크' },
  STATUS_CHANGE: { icon: RefreshCw, color: 'text-gray-500 bg-gray-50', label: '상태변경' },
  DOCUMENT: { icon: File, color: 'text-teal-500 bg-teal-50', label: '문서' },
  SYSTEM: { icon: Bot, color: 'text-gray-400 bg-gray-50', label: '시스템' }
};

// 날짜 그룹핑 헬퍼
const groupByDate = (items: TimelineItem[]) => {
  const groups: Record<string, TimelineItem[]> = {};
  const today = new Date().toDateString();
  const yesterday = new Date(Date.now() - 86400000).toDateString();

  items.forEach(item => {
    const date = new Date(item.date).toDateString();
    let label: string;
    
    if (date === today) {
      label = '오늘';
    } else if (date === yesterday) {
      label = '어제';
    } else {
      label = new Date(item.date).toLocaleDateString('ko-KR', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    }

    if (!groups[label]) {
      groups[label] = [];
    }
    groups[label].push(item);
  });

  return groups;
};

// 시간 포맷팅
const formatTime = (dateStr: string) => {
  return new Date(dateStr).toLocaleTimeString('ko-KR', {
    hour: '2-digit',
    minute: '2-digit'
  });
};

// 활동 아이템 컴포넌트
const ActivityItem: React.FC<{ item: TimelineItem }> = ({ item }) => {
  const config = activityConfig[item.type];
  const Icon = config.icon;

  return (
    <div className="flex gap-3 py-3">
      <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center ${config.color}`}>
        <Icon className="w-4 h-4" />
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1">
          <span className="text-sm font-medium">{formatTime(item.date)}</span>
          <span className="text-sm text-muted-foreground">{item.subject}</span>
          {item.isAutoGenerated && (
            <Badge variant="outline" className="text-xs">자동</Badge>
          )}
        </div>
        {item.content && (
          <p className="text-sm text-muted-foreground whitespace-pre-wrap">
            "{item.content}"
          </p>
        )}
        {item.metadata?.nextAction && (
          <div className="mt-1 text-xs text-muted-foreground">
            다음 액션: {item.metadata.nextAction}
            {item.metadata.nextDate && ` (${new Date(item.metadata.nextDate).toLocaleDateString('ko-KR')})`}
          </div>
        )}
        <div className="flex items-center gap-2 mt-1 text-xs text-muted-foreground">
          <User className="w-3 h-3" />
          <span>{item.user.name}</span>
        </div>
      </div>
    </div>
  );
};

// 활동 추가 폼 컴포넌트
const ActivityForm: React.FC<{
  entityType: string;
  entityId: string;
  onSubmit: (activity: CreateActivityInput) => void;
  onCancel: () => void;
}> = ({ entityType, entityId, onSubmit, onCancel }) => {
  const [type, setType] = useState<ActivityType>('NOTE');
  const [subject, setSubject] = useState('');
  const [content, setContent] = useState('');
  const [nextAction, setNextAction] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!subject.trim()) return;

    onSubmit({
      entityType,
      entityId,
      type,
      subject,
      content: content || undefined,
      metadata: nextAction ? { nextAction } : undefined
    });

    setSubject('');
    setContent('');
    setNextAction('');
  };

  return (
    <Card className="mb-4">
      <CardContent className="pt-4">
        <form onSubmit={handleSubmit} className="space-y-3">
          <div className="flex gap-2">
            <Select value={type} onValueChange={(v) => setType(v as ActivityType)}>
              <SelectTrigger className="w-32">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="CALL">📞 전화</SelectItem>
                <SelectItem value="EMAIL">📧 이메일</SelectItem>
                <SelectItem value="MEETING">👥 미팅</SelectItem>
                <SelectItem value="NOTE">📝 메모</SelectItem>
              </SelectContent>
            </Select>
            <Input
              placeholder="제목/요약"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="flex-1"
            />
          </div>
          <Textarea
            placeholder="상세 내용 (선택)"
            value={content}
            onChange={(e) => setContent(e.target.value)}
            rows={2}
          />
          <Input
            placeholder="다음 액션 (선택)"
            value={nextAction}
            onChange={(e) => setNextAction(e.target.value)}
          />
          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" size="sm" onClick={onCancel}>
              취소
            </Button>
            <Button type="submit" size="sm" disabled={!subject.trim()}>
              저장
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
};

// 메인 타임라인 컴포넌트
export const ActivityTimeline: React.FC<ActivityTimelineProps> = ({
  entityType,
  entityId,
  timeline,
  onActivityAdd,
  showForm = true,
  isLoading = false
}) => {
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [filterType, setFilterType] = useState<ActivityType | 'ALL'>('ALL');

  const filteredTimeline = filterType === 'ALL' 
    ? timeline 
    : timeline.filter(item => item.type === filterType);

  const groupedTimeline = groupByDate(filteredTimeline);

  const handleActivityAdd = (activity: CreateActivityInput) => {
    onActivityAdd?.(activity);
    setIsFormOpen(false);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-32">
        <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div>
      {/* 헤더 */}
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-semibold flex items-center gap-2">
          <Clock className="w-4 h-4" />
          활동 기록
        </h3>
        <div className="flex items-center gap-2">
          <Select value={filterType} onValueChange={(v) => setFilterType(v as ActivityType | 'ALL')}>
            <SelectTrigger className="w-28 h-8">
              <Filter className="w-3 h-3 mr-1" />
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="ALL">전체</SelectItem>
              <SelectItem value="CALL">전화</SelectItem>
              <SelectItem value="EMAIL">이메일</SelectItem>
              <SelectItem value="MEETING">미팅</SelectItem>
              <SelectItem value="NOTE">메모</SelectItem>
              <SelectItem value="STATUS_CHANGE">상태변경</SelectItem>
            </SelectContent>
          </Select>
          {showForm && !isFormOpen && (
            <Button size="sm" onClick={() => setIsFormOpen(true)}>
              <Plus className="w-4 h-4 mr-1" />
              활동 추가
            </Button>
          )}
        </div>
      </div>

      {/* 활동 추가 폼 */}
      {isFormOpen && (
        <ActivityForm
          entityType={entityType}
          entityId={entityId}
          onSubmit={handleActivityAdd}
          onCancel={() => setIsFormOpen(false)}
        />
      )}

      {/* 타임라인 */}
      <div className="space-y-4">
        {Object.entries(groupedTimeline).map(([date, items]) => (
          <div key={date}>
            <div className="flex items-center gap-2 mb-2">
              <Calendar className="w-4 h-4 text-muted-foreground" />
              <span className="text-sm font-medium text-muted-foreground">{date}</span>
            </div>
            <Card>
              <CardContent className="py-2 divide-y">
                {items.map((item) => (
                  <ActivityItem key={item.id} item={item} />
                ))}
              </CardContent>
            </Card>
          </div>
        ))}

        {Object.keys(groupedTimeline).length === 0 && (
          <div className="text-center text-muted-foreground py-8">
            활동 기록이 없습니다
          </div>
        )}
      </div>
    </div>
  );
};

export default ActivityTimeline;
