// Clinical Pathology Seed Data
// 임상병리검사 마스터데이터 시드

import { PrismaClient, ClinicalTestCategory, SampleType } from '@prisma/client';

const prisma = new PrismaClient();

const clinicalTestItems = [
  // ==================== CBC (일반혈액학) - 패키지 ====================
  {
    category: ClinicalTestCategory.CBC,
    code: 'CBC',
    nameKr: 'CBC (일반혈액학)',
    nameEn: 'Complete Blood Count',
    unit: null,
    method: 'Flowcytometry',
    unitPrice: 50000,
    isPackage: true,
    packageItems: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'RDW', 'HDW', 'PLT', 'MPV'],
    requiredSampleTypes: [SampleType.WHOLE_BLOOD],
    minSampleVolume: 200,
    requiresItem: null,
    displayOrder: 1,
  },
  
  // ==================== DIFF (백혈구감별) - 패키지 ====================
  {
    category: ClinicalTestCategory.DIFF,
    code: 'DIFF',
    nameKr: 'DIFF (백혈구감별계수)',
    nameEn: 'WBC Differential Count',
    unit: null,
    method: 'Flowcytometry, Peroxidase staining',
    unitPrice: 50000,
    isPackage: true,
    packageItems: ['NEU', 'LYM', 'MONO', 'EOS', 'BASO', 'LUC'],
    requiredSampleTypes: [SampleType.WHOLE_BLOOD],
    minSampleVolume: 200,
    requiresItem: 'CBC',
    displayOrder: 2,
  },
  
  // ==================== RETIC (망상적혈구) ====================
  {
    category: ClinicalTestCategory.RETIC,
    code: 'RETIC',
    nameKr: 'RETIC (망상적혈구)',
    nameEn: 'Reticulocyte',
    unit: '%',
    method: 'Flowcytometry, Isovolumetry',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.WHOLE_BLOOD],
    minSampleVolume: 200,
    requiresItem: null,
    displayOrder: 3,
  },
  
  // ==================== 혈액생화학 - 일반 (10,000원/항목) ====================
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'AST',
    nameKr: 'AST',
    nameEn: 'Aspartate aminotransferase',
    unit: 'U/L',
    method: 'Kinetic UV법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 10,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'ALT',
    nameKr: 'ALT',
    nameEn: 'Alanine aminotransferase',
    unit: 'U/L',
    method: 'Kinetic UV법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 11,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'ALP',
    nameKr: 'ALP',
    nameEn: 'Alkaline phosphatase',
    unit: 'U/L',
    method: 'Kinetic colour법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 12,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'BUN',
    nameKr: 'BUN',
    nameEn: 'Blood urea nitrogen',
    unit: 'mg/dL',
    method: 'Urease-UV법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 13,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'CRE',
    nameKr: 'CRE',
    nameEn: 'Creatinine',
    unit: 'mg/dL',
    method: 'Jaffe법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 14,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'GLU',
    nameKr: 'GLU',
    nameEn: 'Glucose',
    unit: 'mg/dL',
    method: 'Enzymatic UV법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 15,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'TCHO',
    nameKr: 'TCHO',
    nameEn: 'Total cholesterol',
    unit: 'mg/dL',
    method: 'Kinetic colour법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 16,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'TPRO',
    nameKr: 'TPRO',
    nameEn: 'Total protein',
    unit: 'g/L',
    method: 'Biuret법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 17,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'CPK',
    nameKr: 'CPK',
    nameEn: 'Creatine phosphokinase',
    unit: 'U/L',
    method: 'Kinetic UV법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 18,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'ALB',
    nameKr: 'ALB',
    nameEn: 'Albumin',
    unit: 'g/dL',
    method: 'BCG 법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 19,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'TBIL',
    nameKr: 'TBIL',
    nameEn: 'Total bilirubin',
    unit: 'mg/dL',
    method: 'Photometric colour법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 20,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'TG',
    nameKr: 'TG',
    nameEn: 'Triglyceride',
    unit: 'mg/dL',
    method: 'Enzyme colour법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 21,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'IP',
    nameKr: 'IP',
    nameEn: 'Inorganic phosphorus',
    unit: 'mg/dL',
    method: 'Photometric UV법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 22,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'CA',
    nameKr: 'Ca',
    nameEn: 'Calcium',
    unit: 'mg/dL',
    method: 'O-CPC 법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 23,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'AG_RATIO',
    nameKr: 'A/G ratio',
    nameEn: 'Albumin/Globulin ratio',
    unit: 'ratio',
    method: 'PRO, ALB로 산출',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 24,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_GENERAL,
    code: 'LDH',
    nameKr: 'LDH',
    nameEn: 'Lactate dehydrogenase',
    unit: 'U/L',
    method: 'Kinetic UV법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 25,
  },

  // ==================== 전해질 - 패키지 (30,000원) ====================
  {
    category: ClinicalTestCategory.ELECTROLYTE,
    code: 'ELECTROLYTE',
    nameKr: '전해질 (Na⁺/K⁺/Cl⁻)',
    nameEn: 'Electrolytes (Sodium/Potassium/Chloride)',
    unit: 'mmol/L',
    method: '이온 선택 전극법',
    unitPrice: 30000,
    isPackage: true,
    packageItems: ['NA', 'K', 'CL'],
    requiredSampleTypes: [SampleType.SERUM, SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 30,
  },
  
  // ==================== 혈액생화학 - 추가 (20,000원/항목) ====================
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'LDL',
    nameKr: 'LDL',
    nameEn: 'Low density lipoprotein cholesterol',
    unit: 'mg/dL',
    method: 'Enzymatic colour법',
    unitPrice: 20000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM],
    minSampleVolume: 300,
    displayOrder: 40,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'HDL',
    nameKr: 'HDL',
    nameEn: 'High density lipoprotein cholesterol',
    unit: 'mg/dL',
    method: 'Enzymatic colour법',
    unitPrice: 20000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM],
    minSampleVolume: 300,
    displayOrder: 41,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'GGT',
    nameKr: 'γ-GTP',
    nameEn: 'Gamma Glutamyl transpeptidase',
    unit: 'U/L',
    method: 'Kinetic colour법',
    unitPrice: 20000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM],
    minSampleVolume: 300,
    displayOrder: 42,
  },
  
  // ==================== 혈액생화학 - 추가 (30,000원/항목) ====================
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'CRP',
    nameKr: 'CRP',
    nameEn: 'C-reactive protein',
    unit: 'mg/L',
    method: 'Immunoturbidimetric',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM],
    minSampleVolume: 300,
    displayOrder: 50,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'UA',
    nameKr: 'UA',
    nameEn: 'Uric acid',
    unit: 'mg/dL',
    method: 'Enzymatic colour법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM],
    minSampleVolume: 300,
    displayOrder: 51,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'MA',
    nameKr: 'MA',
    nameEn: 'Magnesium',
    unit: 'mg/dL',
    method: 'Xylidyl blue법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM],
    minSampleVolume: 300,
    displayOrder: 52,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'BICABO',
    nameKr: 'BICABO',
    nameEn: 'Bicarbonate',
    unit: 'mmol/L',
    method: 'Enzymatic법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM],
    minSampleVolume: 300,
    displayOrder: 53,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'CRP_L',
    nameKr: 'CRP-L',
    nameEn: 'C-reactive protein - Latex',
    unit: 'mg/L',
    method: 'Latex immunoturbidimetric',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM],
    minSampleVolume: 300,
    displayOrder: 54,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'MICRO_ALB',
    nameKr: 'micro-ALB',
    nameEn: 'Micro Albumin',
    unit: 'mg/L',
    method: 'Immunoturbidimetric',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.SERUM, SampleType.URINE],
    minSampleVolume: 300,
    displayOrder: 55,
  },
  {
    category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL,
    code: 'HBA1C',
    nameKr: 'HbA1c',
    nameEn: 'Hemoglobin A1c',
    unit: '%',
    method: 'HPLC',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.WHOLE_BLOOD],
    minSampleVolume: 200,
    displayOrder: 56,
  },
  
  // ==================== 혈액응고검사 (10,000원/항목) ====================
  {
    category: ClinicalTestCategory.COAGULATION,
    code: 'PT',
    nameKr: 'PT',
    nameEn: 'Prothrombin Time',
    unit: 'sec',
    method: 'Clotting법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 60,
  },
  {
    category: ClinicalTestCategory.COAGULATION,
    code: 'APTT',
    nameKr: 'APTT',
    nameEn: 'Activated Partial Thromboplastin Time',
    unit: 'sec',
    method: 'Clotting법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 61,
  },
  {
    category: ClinicalTestCategory.COAGULATION,
    code: 'FIB',
    nameKr: 'FIB',
    nameEn: 'Fibrinogen',
    unit: 'mg/dL',
    method: 'Clauss법',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.PLASMA],
    minSampleVolume: 300,
    displayOrder: 62,
  },
  
  // ==================== 요검사 ====================
  {
    category: ClinicalTestCategory.URINALYSIS,
    code: 'UA_GENERAL',
    nameKr: '요 일반검사',
    nameEn: 'Urinalysis - General',
    unit: null,
    method: 'Dipstick, Microscopy',
    unitPrice: 10000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.URINE],
    minSampleVolume: 500,
    displayOrder: 70,
  },
  {
    category: ClinicalTestCategory.URINALYSIS,
    code: 'UA_SEDIMENT',
    nameKr: '요침사검사',
    nameEn: 'Urine Sediment',
    unit: null,
    method: 'Microscopy',
    unitPrice: 20000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.URINE],
    minSampleVolume: 500,
    displayOrder: 71,
  },
  
  // ==================== 요 생화학 (30,000원/항목) ====================
  {
    category: ClinicalTestCategory.URINE_CHEMISTRY,
    code: 'U_UA',
    nameKr: 'U-UA',
    nameEn: 'Urine Uric acid',
    unit: 'mg/dL',
    method: 'Enzymatic colour법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.URINE],
    minSampleVolume: 300,
    displayOrder: 80,
  },
  {
    category: ClinicalTestCategory.URINE_CHEMISTRY,
    code: 'U_MA',
    nameKr: 'U-MA',
    nameEn: 'Urine Magnesium',
    unit: 'mg/dL',
    method: 'Xylidyl blue법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.URINE],
    minSampleVolume: 300,
    displayOrder: 81,
  },
  {
    category: ClinicalTestCategory.URINE_CHEMISTRY,
    code: 'U_BUN',
    nameKr: 'U-BUN',
    nameEn: 'Urine Blood urea nitrogen',
    unit: 'mg/dL',
    method: 'Urease-UV법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.URINE],
    minSampleVolume: 300,
    displayOrder: 82,
  },
  {
    category: ClinicalTestCategory.URINE_CHEMISTRY,
    code: 'U_CRE',
    nameKr: 'U-CRE',
    nameEn: 'Urine Creatinine',
    unit: 'mg/dL',
    method: 'Jaffe법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.URINE],
    minSampleVolume: 300,
    displayOrder: 83,
  },
  {
    category: ClinicalTestCategory.URINE_CHEMISTRY,
    code: 'U_TP',
    nameKr: 'U-TP',
    nameEn: 'Urine Total protein',
    unit: 'mg/dL',
    method: 'Pyrogallol red법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.URINE],
    minSampleVolume: 300,
    displayOrder: 84,
  },
  {
    category: ClinicalTestCategory.URINE_CHEMISTRY,
    code: 'U_CA',
    nameKr: 'U-Ca',
    nameEn: 'Urine Calcium',
    unit: 'mg/dL',
    method: 'O-CPC 법',
    unitPrice: 30000,
    isPackage: false,
    packageItems: [],
    requiredSampleTypes: [SampleType.URINE],
    minSampleVolume: 300,
    displayOrder: 85,
  },
];

const clinicalQcSettings = [
  { category: ClinicalTestCategory.CBC, thresholdCount: 100, qcFee: 400000 },
  { category: ClinicalTestCategory.DIFF, thresholdCount: 100, qcFee: 400000 },
  { category: ClinicalTestCategory.RETIC, thresholdCount: 100, qcFee: 400000 },
  { category: ClinicalTestCategory.CHEMISTRY_GENERAL, thresholdCount: 100, qcFee: 400000 },
  { category: ClinicalTestCategory.ELECTROLYTE, thresholdCount: 100, qcFee: 400000 },
  { category: ClinicalTestCategory.CHEMISTRY_ADDITIONAL, thresholdCount: 100, qcFee: 400000 },
  { category: ClinicalTestCategory.COAGULATION, thresholdCount: 100, qcFee: 400000 },
  { category: ClinicalTestCategory.URINALYSIS, thresholdCount: 100, qcFee: 400000 },
  { category: ClinicalTestCategory.URINE_CHEMISTRY, thresholdCount: 100, qcFee: 400000 },
];

export async function seedClinicalPathology() {
  console.log('🔬 Seeding Clinical Pathology data...');
  
  // 검사항목 시드
  for (const item of clinicalTestItems) {
    await prisma.clinicalTestItem.upsert({
      where: { code: item.code },
      update: item,
      create: item,
    });
  }
  console.log(`  ✓ ${clinicalTestItems.length} test items seeded`);
  
  // QC 설정 시드
  for (const setting of clinicalQcSettings) {
    await prisma.clinicalQcSetting.upsert({
      where: { category: setting.category },
      update: setting,
      create: setting,
    });
  }
  console.log(`  ✓ ${clinicalQcSettings.length} QC settings seeded`);
  
  console.log('✅ Clinical Pathology seed completed');
}

// 직접 실행 시
if (require.main === module) {
  seedClinicalPathology()
    .then(() => prisma.$disconnect())
    .catch((e) => {
      console.error(e);
      prisma.$disconnect();
      process.exit(1);
    });
}
