// Activity API Client
import { api } from './api';

export type ActivityType = 'CALL' | 'EMAIL' | 'MEETING' | 'NOTE' | 'TASK' | 'STATUS_CHANGE' | 'DOCUMENT' | 'SYSTEM';

export interface Activity {
  id: string;
  entityType: string;
  entityId: string;
  type: ActivityType;
  subject: string;
  content?: string;
  metadata?: Record<string, any>;
  contactName?: string;
  contactInfo?: string;
  duration?: number;
  activityDate: string;
  nextAction?: string;
  nextDate?: string;
  attachments?: any[];
  userId: string;
  user?: { id: string; name: string };
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateActivityInput {
  entityType: string;
  entityId: string;
  type: ActivityType;
  subject: string;
  content?: string;
  metadata?: Record<string, any>;
  contactName?: string;
  contactInfo?: string;
  duration?: number;
  activityDate?: string;
  nextAction?: string;
  nextDate?: string;
  attachments?: any[];
}

export interface ActivityQuery {
  entityType?: string;
  entityId?: string;
  type?: ActivityType;
  userId?: string;
  startDate?: string;
  endDate?: string;
  page?: number;
  limit?: number;
}

export interface ActivitiesResponse {
  activities: Activity[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
  summary?: {
    total: number;
    byType: Record<ActivityType, number>;
  };
}

export interface TimelineResponse {
  timeline: Array<{
    id: string;
    type: ActivityType;
    subject: string;
    content?: string;
    date: string;
    user: { id: string; name: string };
    isAutoGenerated: boolean;
    metadata?: Record<string, any>;
  }>;
  entity: any;
}

// 활동 목록 조회
export async function getActivities(query: ActivityQuery): Promise<ActivitiesResponse> {
  const params = new URLSearchParams();
  Object.entries(query).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      params.append(key, String(value));
    }
  });
  
  const queryString = params.toString();
  return api.get(`/activities${queryString ? `?${queryString}` : ''}`);
}

// 활동 생성
export async function createActivity(input: CreateActivityInput): Promise<Activity> {
  return api.post('/activities', input);
}

// 활동 상세 조회
export async function getActivityById(id: string): Promise<Activity> {
  return api.get(`/activities/${id}`);
}

// 활동 수정
export async function updateActivity(id: string, data: Partial<CreateActivityInput>): Promise<Activity> {
  return api.put(`/activities/${id}`, data);
}

// 활동 삭제
export async function deleteActivity(id: string): Promise<{ success: boolean }> {
  return api.delete(`/activities/${id}`);
}

// 엔티티 타임라인 조회
export async function getTimeline(entityType: string, entityId: string): Promise<TimelineResponse> {
  return api.get(`/activities/timeline/${entityType}/${entityId}`);
}

// 예정된 활동 조회
export async function getUpcomingActivities(days?: number): Promise<Activity[]> {
  const params = days ? `?days=${days}` : '';
  return api.get(`/activities/upcoming${params}`);
}
