// src/data/study-models.ts
// 110개 효력시험 모델 데이터 (PDF 추출)
// 웹앱에서 모델 선택 시 기본값으로 사용

import type { StudyModelTemplate } from "../types";

export const STUDY_MODELS: StudyModelTemplate[] = [
  { id:"HF_TAC", title:"Heart Failure (심부전) - TAC", category:"심혈관 질환", categoryCode:"I", species:["C57BL/6 mouse"], speciesRaw:"C57BL/6 mice (male, 9-week)", sex:"male", ageWeeks:9, inductionMethod:"Transverse Aortic Constriction (TAC) 모델", durationWeeks:12, reportWeeks:4, evalItemsRaw:"심장무게, 조직병리 (H&E, Collagen fiber, 침윤 염증세포 수), Hydroxyproline assay", positiveControl:"Pirfenidone, Entresto", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","2-week","4-week"] },
  { id:"HTN_SHR", title:"Hypertension (고혈압) - SHR", category:"심혈관 질환", categoryCode:"I", species:["SD rat"], speciesRaw:"SHR rat (male, 5-week)", sex:"male", ageWeeks:5, inductionMethod:"고혈압 자연 발생", durationWeeks:13, reportWeeks:4, evalItemsRaw:"수축기 혈압 측정", positiveControl:"Amlodipine", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","8-week"] },
  { id:"THROM_ADP", title:"Thrombosis (항혈전) - ADP", category:"혈전·지혈", categoryCode:"II", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Adenosine Diphosphate (ADP; 응고제)", durationWeeks:6, reportWeeks:4, evalItemsRaw:"혈액 응고 시간 측정", positiveControl:"Clopidogrel bisulfate", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","1-day"] },
  { id:"THROM_COL", title:"Thrombosis (항혈전) - Collagen+Epinephrine", category:"혈전·지혈", categoryCode:"II", species:["ICR mouse"], speciesRaw:"ICR mice (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Collagen + Epinephrine", durationWeeks:7, reportWeeks:4, evalItemsRaw:"생존율 측정", positiveControl:"아스피린", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-day","5-day"] },
  { id:"OAB", title:"Overactive Bladder (과민성 방광염)", category:"비뇨기 질환", categoryCode:"III", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 9-week)", sex:"male", ageWeeks:9, inductionMethod:"요도폐색 수술", durationWeeks:7, reportWeeks:4, evalItemsRaw:"요역동학 검사", positiveControl:"Fesoterodine, 5-HMT", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","11-day","3-day","3-day"] },
  { id:"CYP_CYSTITIS", title:"CYP induced cystitis (CYP유도 방광염)", category:"비뇨기 질환", categoryCode:"III", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 9-week)", sex:"male", ageWeeks:9, inductionMethod:"CYP(cyclophosphamide) 75 mg/kg 투여(IP)", durationWeeks:7, reportWeeks:4, evalItemsRaw:"Von Frey test, 방광의 무게, 방광의 조직병리학적 검사", positiveControl:"laluril Prefill", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","7-day","1-day","4-day"] },
  { id:"RENAL_NEPH", title:"Renal Failure (신부전) - Nephrectomy", category:"신장 질환", categoryCode:"IV", species:["SD rat"], speciesRaw:"Wistar rat (male, 5-week)", sex:"male", ageWeeks:5, inductionMethod:"5/6 신장 적출 모델 (Nephrectomy)", durationWeeks:17, reportWeeks:4, evalItemsRaw:"일반증상, 체중변화, 혈액학적 검사", positiveControl:"Mircera", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","2-week","9-week","1-week"] },
  { id:"DN_BTBR", title:"Diabetic Nephropathy (당뇨병성 신증)", category:"신장 질환", categoryCode:"IV", species:["mouse"], speciesRaw:"BTBR ob/ob mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"", durationWeeks:16, reportWeeks:4, evalItemsRaw:"체중, 혈당 및 당화혈색소 측정, 소변 크레아티닌 및 알부민 측정, 조직병리", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["2-week","2-week","5-week","4-week"] },
  { id:"BRONCH_OVA", title:"Chronic Bronchitis (만성 기관지염)", category:"호흡기 질환", categoryCode:"V", species:["BALB/c mouse"], speciesRaw:"BALB/c mice (male, 6-week)", sex:"male", ageWeeks:6, inductionMethod:"Ovalbumin", durationWeeks:17, reportWeeks:4, evalItemsRaw:"BALF 내 백혈구 측정, 혈장 내 Ova-specific IgG1, IgE 측정, 조직병리 (Goblet cell hyperplasia)", positiveControl:"Montelukast", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-day","5-day"] },
  { id:"BRONCH_RELAX", title:"Bronchus Relaxation (기관지 이완)", category:"호흡기 질환", categoryCode:"V", species:["Guinea pig"], speciesRaw:"Guinea Pig (male, 6-week)", sex:"male", ageWeeks:6, inductionMethod:"", durationWeeks:7, reportWeeks:4, evalItemsRaw:"기관지 이완 평가 (Organ Bath)", positiveControl:"Acetylcholine, Carbachol, Histamine", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-week"] },
  { id:"COUGH", title:"Cough (기침)", category:"호흡기 질환", categoryCode:"V", species:["Guinea pig"], speciesRaw:"Guinea Pig (male, 6-week)", sex:"male", ageWeeks:6, inductionMethod:"Citric Acid 분무", durationWeeks:8, reportWeeks:4, evalItemsRaw:"체중, 일반증상, 기침수 측정", positiveControl:"Synatura, Theobromine", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-day","5-day"] },
  { id:"EXPECT", title:"Expectorant Effect, in vivo (거담)", category:"호흡기 질환", categoryCode:"V", species:["ICR mouse"], speciesRaw:"ICR mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"Phenol Red", durationWeeks:7, reportWeeks:4, evalItemsRaw:"페놀레드 측정", positiveControl:"Synatura, Ambroxol hydrochloride", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-day","1-week"] },
  { id:"LUNG_FIB_T", title:"Lung fibrosis (폐섬유화) - Therapeutic", category:"호흡기 질환", categoryCode:"V", species:["C57BL/6 mouse"], speciesRaw:"C57BL/6 mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"Bleomycin", durationWeeks:18, reportWeeks:4, evalItemsRaw:"Hematological analysis (BALF), Micro-CT, Histological analysis", positiveControl:"Dexamethasone", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","4-week","8-week"] },
  { id:"LUNG_FIB_P", title:"Lung fibrosis (폐섬유화) - Preventive", category:"호흡기 질환", categoryCode:"V", species:["C57BL/6 mouse"], speciesRaw:"C57BL/6 mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"Bleomycin", durationWeeks:16, reportWeeks:4, evalItemsRaw:"Hematological analysis (BALF), Micro-CT, Histological analysis", positiveControl:"Dexamethasone", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","3-week","8-week","4-week"] },
  { id:"DEM_SCOP", title:"Dementia (치매) - Scopolamine, ICR", category:"중추신경계 질환", categoryCode:"VI", species:["ICR mouse"], speciesRaw:"ICR mice (male, 12-week)", sex:"male", ageWeeks:12, inductionMethod:"Scopolamine", durationWeeks:14, reportWeeks:4, evalItemsRaw:"체중, 일반증상, 행동실험 (수미로)", positiveControl:"Aricept", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","4-week","3-day","4-week"] },
  { id:"DEM_AB_C57", title:"Dementia (치매) - b-amyloid, C57BL/6", category:"중추신경계 질환", categoryCode:"VI", species:["C57BL/6 mouse"], speciesRaw:"C57BL/6 mice (male, 12-week)", sex:"male", ageWeeks:12, inductionMethod:"b-amyloid (1-42) / 뇌실내 투여", durationWeeks:9, reportWeeks:4, evalItemsRaw:"체중, 일반증상, 행동실험 (수미로)", positiveControl:"Aricept", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","3-week","1-day","1-week"] },
  { id:"DEM_AB_ICR", title:"Dementia (치매) - b-amyloid, ICR", category:"중추신경계 질환", categoryCode:"VI", species:["ICR mouse"], speciesRaw:"ICR mice (male, 5-week)", sex:"male", ageWeeks:5, inductionMethod:"b-amyloid (1-42) / 뇌실내 투여", durationWeeks:7, reportWeeks:4, evalItemsRaw:"체중, 일반증상, 행동실험 (Passive avoidance test)", positiveControl:"Aricept", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-day","3-day"] },
  { id:"DEM_AB_BALB", title:"Dementia (치매) - b-amyloid, BALB/c", category:"중추신경계 질환", categoryCode:"VI", species:["BALB/c mouse"], speciesRaw:"BALB/c mice (male, 12-week)", sex:"male", ageWeeks:12, inductionMethod:"b-amyloid (1-42) / 뇌실내 투여", durationWeeks:9, reportWeeks:4, evalItemsRaw:"체중, 일반증상, 행동실험 (수미로)", positiveControl:"Aricept", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","4-day"] },
  { id:"STROKE_MCAO", title:"Stroke (뇌졸중) - MCAO", category:"중추신경계 질환", categoryCode:"VI", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rats (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Middle Cerebral Artery Occlusion (MCAO) 수술", durationWeeks:7, reportWeeks:4, evalItemsRaw:"Infarct volume, edema, neurological severity score", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-week","1-week"] },
  { id:"MOTOR_ROT", title:"Motor Coordination (운동협조능) - Rotarod", category:"중추신경계 질환", categoryCode:"VI", species:["ICR mouse"], speciesRaw:"ICR mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"", durationWeeks:10, reportWeeks:4, evalItemsRaw:"체중, 일반증상, 행동실험 (Rotarod)", positiveControl:"Diazepam", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","4-week","1-week"] },
  { id:"MSA", title:"Multiple System Atrophy (다계통 위축증)", category:"중추신경계 질환", categoryCode:"VI", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male/female, 9-week)", sex:"both", ageWeeks:9, inductionMethod:"6-OHDA 또는 quinolinic acid 뇌내 투여", durationWeeks:12, reportWeeks:4, evalItemsRaw:"Cylinder test", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","8-week","1-week"] },
  { id:"SCI", title:"Spinal cord injury (척추손상모델)", category:"중추신경계 질환", categoryCode:"VI", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rats (female, 7-week)", sex:"female", ageWeeks:7, inductionMethod:"Thoracic vertebrae #10에 Impactor 장비로 contusion", durationWeeks:24, reportWeeks:4, evalItemsRaw:"Von Frey test, Grid walk test, BBB score, 조직병리학적 검사", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","12-week","6-week"] },
  { id:"ALS", title:"Amyotrophic Lateral Sclerosis (ALS, 루게릭)", category:"중추신경계 질환", categoryCode:"VI", species:["ALS transgenic mouse"], speciesRaw:"ALS transgenic mouse (B6SJL-Tg(SOD1-G93A)1Gru/J)", sex:"male", ageWeeks:null, inductionMethod:"모체를 수입하여 breeding 후 8주차부터 실험", durationWeeks:40, reportWeeks:4, evalItemsRaw:"생존율, 행동실험, micro-CT, Western blot, 조직병리학적 검사", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["8-week","8-week","12-week","8-week"] },
  { id:"ANALG_HP", title:"Analgesia (진통) - Hot Plate", category:"진통·소염", categoryCode:"VII", species:["ICR mouse"], speciesRaw:"ICR mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"Hot Plate", durationWeeks:6, reportWeeks:4, evalItemsRaw:"Licking response", positiveControl:"Morphine-HCl", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day"] },
  { id:"ANALG_LOCO", title:"Analgesia (진통) - 자발운동량", category:"진통·소염", categoryCode:"VII", species:["ICR mouse"], speciesRaw:"ICR mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"", durationWeeks:6, reportWeeks:4, evalItemsRaw:"Spontaneous Locomotor Activity", positiveControl:"Diazepam", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","1-day"] },
  { id:"ANALG_FORM", title:"Analgesia (진통) - Formalin Test", category:"진통·소염", categoryCode:"VII", species:["ICR mouse"], speciesRaw:"ICR mice (male, 5-week)", sex:"male", ageWeeks:5, inductionMethod:"1% 포르말린 용액 발바닥 피하투여", durationWeeks:7, reportWeeks:4, evalItemsRaw:"Biting 및 licking 시간 측정", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-week","1-week"] },
  { id:"ANALG_AA", title:"Analgesia (진통) - Acetic Acid", category:"진통·소염", categoryCode:"VII", species:["ICR mouse"], speciesRaw:"ICR mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"Acetic Acid", durationWeeks:6, reportWeeks:4, evalItemsRaw:"writhing syndrome 횟수 측정", positiveControl:"Ketoprofen", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","4-week","1-week"] },
  { id:"CCI", title:"Chronic Pain (만성통증) - CCI", category:"진통·소염", categoryCode:"VII", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Chronic Constriction Injury (CCI)", durationWeeks:10, reportWeeks:4, evalItemsRaw:"체중, 일반증상, Hot Plate Test, Von Frey Test, Randall Selitto Test", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","3-week","1-week"] },
  { id:"DN_STZ", title:"Diabetic Neuropathy (당뇨병성 신경병증) - STZ", category:"진통·소염", categoryCode:"VII", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Streptozotocin (STZ)", durationWeeks:12, reportWeeks:4, evalItemsRaw:"체중, 일반증상, Von Frey Test", positiveControl:"Gabapentin", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","1-day","6-week"] },
  { id:"OA_MIA", title:"Osteoarthritis (퇴행성 관절염) - MIA", category:"관절염·면역", categoryCode:"VIII", species:["SD rat"], speciesRaw:"SD rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Monosodium iodoacetate (MIA)", durationWeeks:14, reportWeeks:4, evalItemsRaw:"체중, Incapacitance Tester, 조직병리 (Mankin score), Micro CT", positiveControl:"Naproxen, Aragan", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","4-week","4-week"] },
  { id:"RA_AIA", title:"Rheumatoid arthritis (류마티스 관절염) - AIA", category:"관절염·면역", categoryCode:"VIII", species:["SD rat"], speciesRaw:"Lewis rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Adjuvant-induced Arthritis (AIA) 모델", durationWeeks:14, reportWeeks:4, evalItemsRaw:"관절염 지수 측정, 조직병리, Micro CT", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","4-week","4-week"] },
  { id:"RA_CARR", title:"Rheumatoid arthritis (류마티스 관절염) - Carrageenan", category:"관절염·면역", categoryCode:"VIII", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Carrageenan", durationWeeks:6, reportWeeks:4, evalItemsRaw:"체중, 일반증상, 부종 증가율, Micro CT", positiveControl:"Diclofenac sodium salt", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week"] },
  { id:"RA_CIA", title:"Rheumatoid arthritis (류마티스 관절염) - CIA", category:"관절염·면역", categoryCode:"VIII", species:["DBA1/J mouse"], speciesRaw:"DBA1/J mice (male, 5-week)", sex:"male", ageWeeks:5, inductionMethod:"Collagen-induced Arthritis (CIA) 모델", durationWeeks:16, reportWeeks:4, evalItemsRaw:"관절염 지수 측정, 조직병리 (H&E), Micro CT", positiveControl:"Ibrutinib", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","4-week","1-week"] },
  { id:"OA_ACLT", title:"Osteoarthritis (퇴행성 관절염) - ACLT", category:"관절염·면역", categoryCode:"VIII", species:["NZW rabbit"], speciesRaw:"New zealand white rabbit (male, 최소 9-month)", sex:"male", ageWeeks:36, inductionMethod:"ACLT (전방 십자인대 절단, 반월판 ½ 제거)", durationWeeks:14, reportWeeks:4, evalItemsRaw:"체중, MRI, Micro-CT 조직병리 (Mankin score, IHC)", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","5-week","4-week","8-week"] },
  { id:"CONSTIP", title:"Constipation (변비)", category:"소화기 질환", categoryCode:"IX", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (female, 6-week)", sex:"female", ageWeeks:6, inductionMethod:"Loperamide", durationWeeks:10, reportWeeks:4, evalItemsRaw:"체중, 변 개수, 변 중량, 변 수분함량, 맹장 내용물 pH", positiveControl:"Fibersol-2", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","4-week","3-day","1-day"] },
  { id:"GASTRIC_ACT", title:"Gastric Activity (위액분비능)", category:"소화기 질환", categoryCode:"IX", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rats (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"유문부 및 분문부 결찰", durationWeeks:6, reportWeeks:4, evalItemsRaw:"위액량, pH, 총 산도, 위 손상 면적", positiveControl:"Ranitidine hydrochloride", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["8-hour","1-week","1-week"] },
  { id:"GASTRIC_ASP", title:"Gastric Lesions (위염) - Aspirin", category:"소화기 질환", categoryCode:"IX", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Aspirin", durationWeeks:6, reportWeeks:4, evalItemsRaw:"체중, 일반증상, 위 손상길이, 위 손상면적", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","2-day","1-day","1-day"] },
  { id:"HANGOVER", title:"Hangover (숙취해소)", category:"소화기 질환", categoryCode:"IX", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Ethanol", durationWeeks:6, reportWeeks:4, evalItemsRaw:"에탄올, 아세트 알데히드", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","1-week"] },
  { id:"HYPERL_RAT", title:"Hyperlipidemia (고지혈증) - Rat", category:"대사성 질환", categoryCode:"X", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 5-week)", sex:"male", ageWeeks:5, inductionMethod:"AIN-76 + 1% cholesterol + 0.5% cholic acid", durationWeeks:14, reportWeeks:4, evalItemsRaw:"체중, 사료섭취량, 혈액생화학검사, 지방량 측정", positiveControl:"Metformin hydrochloride", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","4-week","1-week","4-week"] },
  { id:"OBESITY_DIO", title:"Obesity (비만) - DIO", category:"대사성 질환", categoryCode:"X", species:["C57BL/6 mouse"], speciesRaw:"C57BL/6 mice (male, 3-week)", sex:"male", ageWeeks:3, inductionMethod:"Diet induced obesity (DIO)모델, 60% 고지방식이", durationWeeks:19, reportWeeks:4, evalItemsRaw:"복부 지방량 측정, 혈액생화학검사, hepatic TG, hepatic TCHO", positiveControl:"제니칼", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","8-week","2-week","4-week"] },
  { id:"DM1_STZ", title:"Type 1 DM (제1형 당뇨)", category:"대사성 질환", categoryCode:"X", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"Streptozotocin (STZ)", durationWeeks:14, reportWeeks:4, evalItemsRaw:"체중, 사료섭취량, 음수섭취량, 혈당, 혈액생화학적 검사", positiveControl:"Metformin hydrochloride", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","4-day","4-day"] },
  { id:"DM2_DBDB", title:"Type 2 DM (제2형 당뇨)", category:"대사성 질환", categoryCode:"X", species:["db/db mouse"], speciesRaw:"db/db mice (male, 6-week)", sex:"male", ageWeeks:6, inductionMethod:"db/db mice", durationWeeks:10, reportWeeks:4, evalItemsRaw:"체중, 혈당, OGTT, Insulin 측정, 혈액생화학적 검사, 조직병리 (H&E)", positiveControl:"Metformin hydrochloride", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","4-week","1-day","1-week"] },
  { id:"MENO_HF", title:"Menopause (갱년기) - Hot Flashes Test", category:"내분비 질환", categoryCode:"XI", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (female, 12-week)", sex:"female", ageWeeks:12, inductionMethod:"Oophorectomy (난소적출)", durationWeeks:15, reportWeeks:4, evalItemsRaw:"꼬리온도 측정, 혈액생화학", positiveControl:"E2 (estradiol)", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","8-week","1-week"] },
  { id:"AD_DNCB", title:"Atopic Dermatitis (아토피성 피부염)", category:"피부 질환", categoryCode:"XII", species:["mouse"], speciesRaw:"NC/Nga mice (male, 6-week)", sex:"male", ageWeeks:6, inductionMethod:"Dinitrochlorobenzene (DNCB)", durationWeeks:14, reportWeeks:4, evalItemsRaw:"체중, IgE, IL-4, IL-13, IFN-g, 관능평가, 스크래치측정, 조직병리", positiveControl:"Dexamethasone", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-week","4-week","4-week"] },
  { id:"WOUND", title:"Wound (창상)", category:"피부 질환", categoryCode:"XII", species:["BALB/c mouse"], speciesRaw:"BALB/c nude mice (male, 7-week)", sex:"male", ageWeeks:7, inductionMethod:"8mm biopsy punch로 창상 유발", durationWeeks:8, reportWeeks:4, evalItemsRaw:"사진촬영, 창상면적, 조직병리", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","2-week","1-week"] },
  { id:"HAIR_GROWTH", title:"Hair Growth (발모)", category:"피부 질환", categoryCode:"XII", species:["C57BL/6 mouse"], speciesRaw:"C57BL/6 mice (male, 6-week)", sex:"male", ageWeeks:6, inductionMethod:"제모", durationWeeks:12, reportWeeks:4, evalItemsRaw:"체중, 발모 면적(%), 조직병리 (모낭 주기별 분석, 피부두께 측정)", positiveControl:"미녹시딜", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","3-week","4-week"] },
  { id:"BREAST_MCF7", title:"Breast Cancer (유방암) - MCF-7", category:"항암", categoryCode:"XIII", species:["BALB/c mouse"], speciesRaw:"BALB/c nude mice (female, 5-week)", sex:"female", ageWeeks:5, inductionMethod:"MCF-7 cell, xenograft", durationWeeks:13, reportWeeks:4, evalItemsRaw:"종양부피, 종양무게, 사진촬영", positiveControl:"Adriamycin (Doxorubicin)", isInVitro:false, cellLine:"MCF-7", cultureCondition:"10% FBS in RPMI 1640", scheduleDurations:["2-week","1-week","2-week","4-week"] },
  { id:"COLON_COLO205", title:"Colon Cancer (대장암) - Colo 205", category:"항암", categoryCode:"XIII", species:["BALB/c mouse"], speciesRaw:"BALB/c nude mice (male, 5-week)", sex:"male", ageWeeks:5, inductionMethod:"Colo 205 cell, xenograft", durationWeeks:13, reportWeeks:4, evalItemsRaw:"종양부피, 종양무게, 사진촬영", positiveControl:"Adriamycin (Doxorubicin)", isInVitro:false, cellLine:"Colo 205", cultureCondition:"10% FBS in RPMI 1640", scheduleDurations:["2-week","1-week","2-week","4-week"] },
  { id:"LUNG_A549", title:"Lung Cancer (폐암) - A549", category:"항암", categoryCode:"XIII", species:["BALB/c mouse"], speciesRaw:"BALB/c nude mice (male, 5-week)", sex:"male", ageWeeks:5, inductionMethod:"A549 cell, xenograft", durationWeeks:13, reportWeeks:4, evalItemsRaw:"종양부피, 종양무게, 사진촬영", positiveControl:"Adriamycin (Doxorubicin)", isInVitro:false, cellLine:"A549", cultureCondition:"10% FBS in RPMI 1640", scheduleDurations:["2-week","1-week","2-week","4-week"] },
  { id:"ALC_LIVER", title:"Alcoholic Fatty Liver (알코올성 지방간)", category:"간질환", categoryCode:"XV", species:["C57BL/6 mouse"], speciesRaw:"C57BL/6J mice (male, 6-week)", sex:"male", ageWeeks:6, inductionMethod:"Alcoholic Diet", durationWeeks:17, reportWeeks:4, evalItemsRaw:"간 조직 내 TG, TC, TNF-a, 혈액생화학적 변화, 조직병리", positiveControl:"Silymarin", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","6-week","2-week","4-week"] },
  { id:"LIVER_BDL", title:"Liver Cirrhosis (간경화) - BDL", category:"간질환", categoryCode:"XV", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 9-week)", sex:"male", ageWeeks:9, inductionMethod:"Bile Duct Ligation (BDL) 수술", durationWeeks:15, reportWeeks:4, evalItemsRaw:"체중, 혈액생화학적 변화, 조직병리, ELISA, 장기무게, RT-PCR", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","2-week","4-week","4-week"] },
  { id:"BIODEG", title:"Biodegrability test (생분해성)", category:"기타 질환", categoryCode:"XVI", species:["SD rat"], speciesRaw:"SD rat", sex:"male", ageWeeks:7, inductionMethod:"피하 이식", durationWeeks:12, reportWeeks:10, evalItemsRaw:"인장강도, Holding force, 조직병리, 실무게측정", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","12-week","10-week"] },
  { id:"SEPSIS_LPS", title:"Sepsis (패혈증) - LPS", category:"기타 질환", categoryCode:"XVI", species:["ICR mouse"], speciesRaw:"ICR mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"LPS", durationWeeks:6, reportWeeks:4, evalItemsRaw:"생존율, 체중, 혈액생화학, 조직병리", positiveControl:"Dexamethasone", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","1-day","1-week"] },
  { id:"PERIO", title:"Periodontitis (치주염) - 대구치 결찰", category:"기타 질환", categoryCode:"XVI", species:["SD rat"], speciesRaw:"Sprague-Dawley (SD) rat (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"대구치 결찰", durationWeeks:14, reportWeeks:4, evalItemsRaw:"Micro-CT, 조직병리", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","2-week","4-week","4-week"] },
  { id:"MUSCLE", title:"Muscle improvement (근력개선)", category:"기타 질환", categoryCode:"XVI", species:["ICR mouse"], speciesRaw:"ICR mice (male, 8-week)", sex:"male", ageWeeks:8, inductionMethod:"", durationWeeks:10, reportWeeks:4, evalItemsRaw:"근력측정, 혈액생화학, 조직병리", positiveControl:"", isInVitro:false, cellLine:"", cultureCondition:"", scheduleDurations:["1-week","4-week","1-week"] },
];

// Category 목록
export const STUDY_CATEGORIES = [
  { code: "I", name: "심혈관 질환" },
  { code: "II", name: "혈전·지혈" },
  { code: "III", name: "비뇨기 질환" },
  { code: "IV", name: "신장 질환" },
  { code: "V", name: "호흡기 질환" },
  { code: "VI", name: "중추신경계 질환" },
  { code: "VII", name: "진통·소염" },
  { code: "VIII", name: "관절염·면역" },
  { code: "IX", name: "소화기 질환" },
  { code: "X", name: "대사성 질환" },
  { code: "XI", name: "내분비 질환" },
  { code: "XII", name: "피부 질환" },
  { code: "XIII", name: "항암" },
  { code: "XIV", name: "항균" },
  { code: "XV", name: "간질환" },
  { code: "XVI", name: "기타 질환" },
] as const;

export function getModelsByCategory(category: string): StudyModelTemplate[] {
  return STUDY_MODELS.filter(m => m.category === category);
}

export function getModelById(id: string): StudyModelTemplate | undefined {
  return STUDY_MODELS.find(m => m.id === id);
}
