// ============================================================
// 코아스템켐온 효력시험 모델 데이터 (110개 전체)
// 원본: 코아스템켐온_신약개발지원본부_2025_유효성시험_국문.pdf
// schedule_durations: 주령혼입 제거, 순화기간(1-week) 반영 완료
// ============================================================

export type CategoryCode =
  | 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI' | 'VII' | 'VIII'
  | 'IX' | 'X' | 'XI' | 'XII' | 'XIII' | 'XIV' | 'XV' | 'XVI' | 'ETC';

export interface StudyModel {
  id: string;
  title: string;
  titleEn: string;
  titleKr: string;
  categoryCode: CategoryCode;
  category: string;
  species: string[];
  speciesRaw: string;
  sex: 'male' | 'female' | 'both' | '';
  ageWeeks: number;
  inductionMethod: string;
  durationWeeks: number;
  reportWeeks: number;
  evalItemsRaw: string;
  positiveControl: string;
  isInVitro: boolean;
  cellLine: string;
  cultureCondition: string;
  scheduleDurations: string[];
  page: number;
}

export interface CategoryInfo {
  code: CategoryCode;
  name: string;
  nameEn: string;
  modelCount: number;
}

export const CATEGORIES: CategoryInfo[] = [
  { code: 'I', name: '심혈관 질환', nameEn: 'Cardiovascular', modelCount: 2 },
  { code: 'II', name: '혈전·지혈', nameEn: 'Thrombosis & Hemostasis', modelCount: 2 },
  { code: 'III', name: '비뇨기 질환', nameEn: 'Urology', modelCount: 2 },
  { code: 'IV', name: '신장 질환', nameEn: 'Nephrology', modelCount: 2 },
  { code: 'V', name: '호흡기 질환', nameEn: 'Respiratory', modelCount: 6 },
  { code: 'VI', name: '중추신경계 질환', nameEn: 'Neuroscience', modelCount: 9 },
  { code: 'VII', name: '진통·소염', nameEn: 'Pain & Analgesia', modelCount: 9 },
  { code: 'VIII', name: '관절염·면역', nameEn: 'Musculoskeletal & Immune', modelCount: 8 },
  { code: 'IX', name: '소화기 질환', nameEn: 'Gastroenterology', modelCount: 10 },
  { code: 'X', name: '대사성 질환', nameEn: 'Metabolic Disease', modelCount: 9 },
  { code: 'XI', name: '내분비 질환', nameEn: 'Menopause', modelCount: 2 },
  { code: 'XII', name: '피부 질환', nameEn: 'Dermatology', modelCount: 11 },
  { code: 'XIII', name: '항암', nameEn: 'Oncology', modelCount: 15 },
  { code: 'XIV', name: '항균', nameEn: 'Anti-infection', modelCount: 4 },
  { code: 'XV', name: '간질환', nameEn: 'Hepatology', modelCount: 6 },
  { code: 'XVI', name: '기타 질환', nameEn: 'Others', modelCount: 11 },
  { code: 'ETC', name: '', nameEn: 'ETC', modelCount: 2 },
];

export const STUDY_MODELS: StudyModel[] = [
  {
    id: 'I-1', title: 'I-1. Heart Failure (심부전) - TAC',
    titleEn: 'Heart Failure', titleKr: '심부전',
    categoryCode: 'I' as CategoryCode, category: '심혈관 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice (male, 9-week)',
    sex: 'male', ageWeeks: 9,
    inductionMethod: 'Transverse Aortic Constriction (TAC) 모델',
    durationWeeks: 12, reportWeeks: 4,
    evalItemsRaw: '심장무게, 조직병리 (H&E, Collagen fiber, 침윤 염증세포 수), Hydroxyproline assay',
    positiveControl: 'Pirfenidone, Entresto',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "2-week", "4-week"], page: 8,
  },
  {
    id: 'I-2', title: 'I-2. Hypertension (고혈압) - SHR',
    titleEn: 'Hypertension', titleKr: '고혈압',
    categoryCode: 'I' as CategoryCode, category: '심혈관 질환',
    species: ["SHR rat"], speciesRaw: 'SHR rat (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: '고혈압 자연 발생',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '수축기 혈압 측정',
    positiveControl: 'Amlodipine',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "8-week"], page: 9,
  },
  {
    id: 'II-1', title: 'II-1. Thrombosis (항혈전) - ADP',
    titleEn: 'Thrombosis', titleKr: '항혈전',
    categoryCode: 'II' as CategoryCode, category: '혈전·지혈',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Adenosine Diphosphate (ADP; 응고제)',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '혈액 응고 시간 측정',
    positiveControl: 'Clopidogrel bisulfate',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-day"], page: 10,
  },
  {
    id: 'II-2', title: 'II-2. Thrombosis (항혈전) - Collagen',
    titleEn: 'Thrombosis', titleKr: '항혈전',
    categoryCode: 'II' as CategoryCode, category: '혈전·지혈',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Collagen + Epinephrine',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '생존율 측정',
    positiveControl: '아스피린',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-day", "5-day"], page: 11,
  },
  {
    id: 'III-1', title: 'III-1. Overactive Bladder (과민성 방광염)',
    titleEn: 'Overactive Bladder', titleKr: '과민성 방광염',
    categoryCode: 'III' as CategoryCode, category: '비뇨기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 9-week)',
    sex: 'male', ageWeeks: 9,
    inductionMethod: '요도폐색 수술',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '요역동학 검사',
    positiveControl: 'Fesoterodine, 5-HMT',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "11-day", "3-day", "3-day"], page: 12,
  },
  {
    id: 'III-2', title: 'III-2. CYP induced cystitis (CYP유도 방광염)',
    titleEn: '', titleKr: '',
    categoryCode: 'III' as CategoryCode, category: '비뇨기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 9-week)',
    sex: 'male', ageWeeks: 9,
    inductionMethod: 'CYP(cyclophosphamide) 75 mg/kg 투여(IP)',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: 'Von Frey test, 방광의 무게, 방광의 조직병리학적 검사',
    positiveControl: 'laluril Prefill',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "7-day", "1-day", "4-day"], page: 13,
  },
  {
    id: 'VI-1', title: 'VI-1. Renal Failure (신부전) - Nephrectomy',
    titleEn: 'Renal Failure', titleKr: '신부전',
    categoryCode: 'IV' as CategoryCode, category: '신장 질환',
    species: ["Wistar rat"], speciesRaw: 'Wistar rat (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: '5/6 신장 적출 모델 (Nephrectomy)',
    durationWeeks: 17, reportWeeks: 4,
    evalItemsRaw: '일반증상, 체중변화, 혈액학적 검사',
    positiveControl: 'Mircera',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "2-week", "9-week", "1-week"], page: 14,
  },
  {
    id: 'IV-2', title: 'IV-2. Diabetic Nephropathy (당뇨병성 신증)',
    titleEn: 'Diabetic Nephropathy', titleKr: '당뇨병성 신증',
    categoryCode: 'IV' as CategoryCode, category: '신장 질환',
    species: ["BTBR ob/ob mouse"], speciesRaw: 'BTBR W/T (wild type) mice, BTBR ob/ob mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: '',
    durationWeeks: 16, reportWeeks: 4,
    evalItemsRaw: '체중, 혈당 및 당화혈색소 측정, 소변 크레아티닌 및 알부민 측정, 조직병리 (신장의 손상 정도, 사구체 총맥의 면적, 사구체의 경화 정도, 세동맥의 유리질증 정도, 사구체 혈관사이의 기질면적, 사구체 기저막의 두께)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "2-week", "2-week", "5-week", "4-week"], page: 15,
  },
  {
    id: 'V-1', title: 'V-1. Chronic Bronchitis (만성 기관지염)',
    titleEn: 'Chronic Bronchitis', titleKr: '만성 기관지염',
    categoryCode: 'V' as CategoryCode, category: '호흡기 질환',
    species: ["BALB/c mouse"], speciesRaw: 'BALB/c mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'Ovalbumin',
    durationWeeks: 17, reportWeeks: 4,
    evalItemsRaw: 'Bronchoalveolar lavage fluid(BALF) 내 백혈구 측정, 혈장 내 Ova-specific IgG1, IgE 측정, 조직병리 (Goblet cell hyperplasia)',
    positiveControl: 'Montelukast',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-day", "5-day"], page: 16,
  },
  {
    id: 'V-2', title: 'V-2. Bronchus Relaxation (기관지 이완)',
    titleEn: 'Bronchus Relaxation', titleKr: '기관지 이완',
    categoryCode: 'V' as CategoryCode, category: '호흡기 질환',
    species: ["Guinea pig"], speciesRaw: 'Guinea Pig (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: '',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '기관지 이완 평가 (Organ Bath)',
    positiveControl: 'Acetylcholine, Carbachol, Histamine',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-week"], page: 17,
  },
  {
    id: 'V-3', title: 'V-3. Cough (기침)',
    titleEn: 'Cough', titleKr: '기침',
    categoryCode: 'V' as CategoryCode, category: '호흡기 질환',
    species: ["Guinea pig"], speciesRaw: 'Guinea Pig (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'Citric Acid 분무',
    durationWeeks: 8, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 기침수 측정',
    positiveControl: 'Synatura, Theobromine',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-day", "5-day"], page: 18,
  },
  {
    id: 'V-4', title: 'V-4. Expectorant Effect, in vivo (거담)',
    titleEn: 'in vivo', titleKr: '거담',
    categoryCode: 'V' as CategoryCode, category: '호흡기 질환',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'Phenol Red',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '페놀레드 측정',
    positiveControl: 'Synatura, Ambroxol hydrochloride',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-day", "1-week"], page: 19,
  },
  {
    id: 'V-5', title: 'V-5. Fibrosis of lung (폐섬유화_Therapeutic)',
    titleEn: '', titleKr: '',
    categoryCode: 'V' as CategoryCode, category: '호흡기 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'Bleomycin',
    durationWeeks: 18, reportWeeks: 4,
    evalItemsRaw: 'Hematological analysis (BALF), Micro-CT, Histological analysis',
    positiveControl: 'Dexamethasone',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "4-week", "8-week"], page: 20,
  },
  {
    id: 'V-6', title: 'V-6. Fibrosis of lung (폐섬유화_Preventive)',
    titleEn: '', titleKr: '',
    categoryCode: 'V' as CategoryCode, category: '호흡기 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'Bleomycin',
    durationWeeks: 16, reportWeeks: 4,
    evalItemsRaw: 'Hematological analysis (BALF), Micro-CT, Histological analysis',
    positiveControl: 'Dexamethasone',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "3-week", "8-week", "4-week"], page: 21,
  },
  {
    id: 'VI-1', title: 'VI-1. Dementia (치매) - Scopolamine, ICR',
    titleEn: 'Dementia', titleKr: '치매',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 12-week)',
    sex: 'male', ageWeeks: 12,
    inductionMethod: 'Scopolamine',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 행동실험 (수미로)',
    positiveControl: 'Aricept',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "3-day", "4-week"], page: 22,
  },
  {
    id: 'VI-2', title: 'VI-2. Dementia (치매) - b-amyloid, C57BL/6',
    titleEn: 'Dementia', titleKr: '치매',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice (male, 12-week)',
    sex: 'male', ageWeeks: 12,
    inductionMethod: 'b-amyloid (1-42) / 뇌실내 투여',
    durationWeeks: 9, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 행동실험 (수미로)',
    positiveControl: 'Aricept',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "3-week", "1-day", "1-week"], page: 23,
  },
  {
    id: 'VI-3', title: 'VI-3. Dementia (치매) - b-amyloid, ICR',
    titleEn: 'Dementia', titleKr: '치매',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'b-amyloid (1-42) / 뇌실내 투여',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 행동실험 (Passive avoidance test)',
    positiveControl: 'Aricept',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-day", "3-day"], page: 24,
  },
  {
    id: 'VI-4', title: 'VI-4. Dementia (치매) - b-amyloid, BALB/c',
    titleEn: 'Dementia', titleKr: '치매',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["BALB/c mouse"], speciesRaw: 'BALB/c mice (male, 12-week)',
    sex: 'male', ageWeeks: 12,
    inductionMethod: 'b-amyloid (1-42) / 뇌실내 투여',
    durationWeeks: 9, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 행동실험 (수미로)',
    positiveControl: 'Aricept',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "4-day"], page: 25,
  },
  {
    id: 'VI-5', title: 'VI-5. Stroke (뇌졸중) - MCAO',
    titleEn: 'Stroke', titleKr: '뇌졸중',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rats (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Middle Cerebral Artery Occlusion (MCAO) 수술',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: 'Infarct volume, edema, neurological severity score',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-week", "1-week"], page: 26,
  },
  {
    id: 'VI-6', title: 'VI-6. Motor Coordination (운동협조능) - Rotarod',
    titleEn: 'Motor Coordination', titleKr: '운동협조능',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: '',
    durationWeeks: 10, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 행동실험 (Rotarod)',
    positiveControl: 'Diazepam',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "4-week", "1-week"], page: 27,
  },
  {
    id: 'VI-7', title: 'VI-7. Multiple System Atrophy (다계통 위축증)',
    titleEn: 'Multiple System Atrophy', titleKr: '다계통 위축증',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male/female, 9-week)',
    sex: 'male', ageWeeks: 9,
    inductionMethod: '6-Hydroxydopamine hydrochloride (6-OHDA) 또는',
    durationWeeks: 12, reportWeeks: 4,
    evalItemsRaw: 'Cylinder test',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "8-week", "1-week"], page: 28,
  },
  {
    id: 'VI-8', title: 'VI-8. Spinal cord injury (척추 손상 모델)',
    titleEn: 'Spinal cord injury', titleKr: '척추 손상 모델',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rats (female, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Thoracic vertebrae #10에 Impactor 장비로 contusion',
    durationWeeks: 24, reportWeeks: 4,
    evalItemsRaw: 'Von Frey test, Grid walk test, BBB score, 조직병리학적 검사',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "12-week", "6-week"], page: 29,
  },
  {
    id: 'VI-9', title: 'VI-9. Amyotrophic Lateral Sclerosis (ALS, 루게릭)',
    titleEn: '', titleKr: '',
    categoryCode: 'VI' as CategoryCode, category: '중추신경계 질환',
    species: ["ALS transgenic mouse (SOD1-G93A)"], speciesRaw: 'ALS transgenic mouse (B6SJL-Tg(SOD1-G93A)1Gru/J)',
    sex: '', ageWeeks: 0,
    inductionMethod: '모체를 수입하여 breeding 후 8 주차부터 실험)',
    durationWeeks: 40, reportWeeks: 4,
    evalItemsRaw: '생존율, 행동실험, micro-CT, Western blot, 조직병리학적 검사',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["8-week", "8-week", "12-week", "8-week"], page: 30,
  },
  {
    id: 'VII-1', title: 'VII-1. Analgesia (진통) - Hot Plate',
    titleEn: 'Analgesia', titleKr: '진통',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'Hot Plate',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: 'Licking response (시험물질 단회 투여 후 30 분 경과한 후 57 ℃ Hot plate 에 놓고 licking 시작 시간측정)',
    positiveControl: 'Morphine-HCl',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day"], page: 32,
  },
  {
    id: 'VII-2', title: 'VII-2. Analgesia (진통) - 자발운동량',
    titleEn: 'Analgesia', titleKr: '진통',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: '',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: 'Spontaneous Locomotor Activity (시간대별로 동물을 activity monitor의 cage에 넣고 5 분 동안 움직인 운동량(거리) 측정)',
    positiveControl: 'Diazepam',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-day"], page: 33,
  },
  {
    id: 'VII-3', title: 'VII-3. Analgesia (진통) - Formalin Test',
    titleEn: 'Analgesia', titleKr: '진통',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: '1 % 포르말린 용액 발바닥 피하투여',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: 'Biting 및 licking 시간 측정',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-week", "1-week"], page: 34,
  },
  {
    id: 'VII-4', title: 'VII-4. Analgesia (진통) - Acetic Acid',
    titleEn: 'Analgesia', titleKr: '진통',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'Acetic Acid',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '시험물질 단회 투여후 30 분 경과한 후 경련유발물질을 복강내 투여한 10 분 후부터, 10 분간 writhing syndrome 횟수 측정',
    positiveControl: 'Ketoprofen',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "4-week", "1-week"], page: 35,
  },
  {
    id: 'VII-5', title: 'VII-5. Analgesia (진통) - Yeast',
    titleEn: 'Analgesia', titleKr: '진통',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["SD rat"], speciesRaw: 'SD rat (male, 4-week)',
    sex: 'male', ageWeeks: 4,
    inductionMethod: 'Yeast',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '유발물질 투여 4.5 시간 후 시험물질을 단회 투여하고 시간대 별로 Randall-Selitto test로 paw withdrawal threshold (g)를 측정',
    positiveControl: 'Loxoprofen-Na',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-day", "1-day"], page: 36,
  },
  {
    id: 'VII-6', title: 'VII-6. Chronic Pain (만성통증) - CCI',
    titleEn: 'Chronic Pain', titleKr: '만성통증',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Chronic Constriction Injury (CCI)',
    durationWeeks: 10, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, Hot Plate Test, Von Frey Test, Randall Selitto Test',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "3-week", "1-week"], page: 37,
  },
  {
    id: 'VII-7', title: 'VII-7. Diabetic Neuropathy (당뇨병성 신경병증)',
    titleEn: 'Diabetic Neuropathy', titleKr: '당뇨병성 신경병증',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Streptozotocin (STZ)',
    durationWeeks: 12, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, Von Frey Test',
    positiveControl: 'Gabapentin',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-day", "6-week"], page: 38,
  },
  {
    id: 'VII-8', title: 'VII-8. Analgesia (진통) – Capsaicin 유도',
    titleEn: 'Analgesia', titleKr: '진통',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["SD rat"], speciesRaw: 'SD rat (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: '0.3 % Capsaicin 뒷 발바닥 피하 투여',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: 'Von Frey test, Hot plate test',
    positiveControl: 'Botox, gabapentin',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-day", "1-week"], page: 39,
  },
  {
    id: 'VII-9', title: 'VII-9. Analgesia (진통) – 수술 후 통증 유도 모델',
    titleEn: 'Analgesia', titleKr: '진통',
    categoryCode: 'VII' as CategoryCode, category: '진통·소염',
    species: ["SD rat"], speciesRaw: 'SD rat (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: '뒷발바닥 피부 및 근육 절개',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: 'Von Frey test',
    positiveControl: '리도카인',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-week"], page: 40,
  },
  {
    id: 'VIII-1', title: 'VIII-1. Antioxidant Effect, in vitro (피로회복)',
    titleEn: 'in vitro', titleKr: '피로회복',
    categoryCode: 'VIII' as CategoryCode, category: '관절염·면역',
    species: ["C2C12 cell"], speciesRaw: 'C2C12 cell',
    sex: '', ageWeeks: 0,
    inductionMethod: '근육세포 분화, H2O2 로 산화적 손상 유발',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '세포독성, RT-PCR (Mn-Sod, Myod, Mapk1, Bax/Bcl2)',
    positiveControl: '',
    isInVitro: true, cellLine: 'C2C12 cell', cultureCondition: '배양 시 10 % FBS in DMEM',
    scheduleDurations: ["1-week", "2-week", "2-week", "4-week"], page: 41,
  },
  {
    id: 'VIII-2', title: 'VIII-2. Forced Swimming, in vivo (피로회복)',
    titleEn: 'in vivo', titleKr: '피로회복',
    categoryCode: 'VIII' as CategoryCode, category: '관절염·면역',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: '강제 수영 (Forced swimming)',
    durationWeeks: 11, reportWeeks: 4,
    evalItemsRaw: 'Swimming time, LDH, CPK, BUN',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "4-week", "1-week"], page: 42,
  },
  {
    id: 'VIII-3', title: 'VIII-3. Immune Activation (면역활성)',
    titleEn: 'Immune Activation', titleKr: '면역활성',
    categoryCode: 'VIII' as CategoryCode, category: '관절염·면역',
    species: ["BALB/c mouse"], speciesRaw: 'BALB/c mice (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: '시험물질 처리 후 비장세포 및 복강대식세포 분리',
    durationWeeks: 12, reportWeeks: 4,
    evalItemsRaw: '복강대식세포 cytokine (IL-1b, IL-6, TNF-a), 비장세포 증식능',
    positiveControl: 'Ginsenoside',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "1-week", "2-week"], page: 43,
  },
  {
    id: 'VIII-4', title: 'VIII-4. Osteoarthritis (퇴행성 관절염) - MIA',
    titleEn: 'Osteoarthritis', titleKr: '퇴행성 관절염',
    categoryCode: 'VIII' as CategoryCode, category: '관절염·면역',
    species: ["SD rat"], speciesRaw: 'SD rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Monosodium iodoacetate (MIA)',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '체중, Incapacitance Tester, 조직병리 (Mankin score, Hypocellularity, Clone/osteophyte), Micro CT',
    positiveControl: 'Naproxen, Aragan',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "4-week", "4-week"], page: 44,
  },
  {
    id: 'VIII-5', title: 'VIII-5. Rheumatoid Arthritis (류마티스 관절염)',
    titleEn: 'Rheumatoid Arthritis', titleKr: '류마티스 관절염',
    categoryCode: 'VIII' as CategoryCode, category: '관절염·면역',
    species: ["Lewis rat"], speciesRaw: 'Lewis rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Adjuvant-induced Arthritis (AIA) 모델',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '관절염 지수 측정, 조직병리 (Histological semiquantitative score, Tibia articular cartilage), Micro CT',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "4-week", "4-week"], page: 45,
  },
  {
    id: 'VIII-6', title: 'VIII-6. Rheumatoid Arthritis (류마티스 관절염)',
    titleEn: 'Rheumatoid Arthritis', titleKr: '류마티스 관절염',
    categoryCode: 'VIII' as CategoryCode, category: '관절염·면역',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Carrageenan',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 부종 증가율, 부종 억제율, Micro CT',
    positiveControl: 'Diclofenac sodium salt',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week"], page: 46,
  },
  {
    id: 'VIII-7', title: 'VIII-7. Rheumatoid Arthritis (류마티스 관절염)',
    titleEn: 'Rheumatoid Arthritis', titleKr: '류마티스 관절염',
    categoryCode: 'VIII' as CategoryCode, category: '관절염·면역',
    species: ["DBA/1J mouse"], speciesRaw: 'DBA1/J mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'Collagen-induced Arthritis (CIA) 모델, 콜라겐 투여',
    durationWeeks: 16, reportWeeks: 4,
    evalItemsRaw: '관절염 지수 측정, 조직병리 (H&E stain, Histological semiquantitative score, Tibia articular cartilige), Micro CT',
    positiveControl: 'Ibrutinib',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "4-week", "1-week"], page: 47,
  },
  {
    id: 'VIII-8', title: 'VIII-8. Osteoarthritis -ACLT',
    titleEn: '', titleKr: '',
    categoryCode: 'VIII' as CategoryCode, category: '관절염·면역',
    species: ["NZW rabbit"], speciesRaw: 'New zealand white rabbit (male, 최소 9-month)',
    sex: 'male', ageWeeks: 0,
    inductionMethod: 'ACLT (전방 십자인대 절단, 반월판 ½ 제거)',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '체중, MRI, Micro-CT 조직병리 (Mankin score, Hypocellularity, Clone/osteophyte, IHC)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "8-week"], page: 48,
  },
  {
    id: 'IX-1', title: 'IX-1. Constipation (변비)',
    titleEn: 'Constipation', titleKr: '변비',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (female, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'Loperamide',
    durationWeeks: 10, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 변 개수, 변 중량, 변 수분함량, 맹장 내용물 pH, 장 내 변 개수',
    positiveControl: 'Fibersol-2 (마츠다니)',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "3-day", "1-day"], page: 49,
  },
  {
    id: 'IX-2', title: 'IX-2. Gastric Activity (위액분비능)',
    titleEn: 'Gastric Activity', titleKr: '위액분비능',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rats (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: '유문부 및 분문부 결찰',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '위액량, pH, 총 산도, 위 손상 면적',
    positiveControl: 'Ranitidine hydrochloride',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "8-hour", "1-week", "1-week"], page: 50,
  },
  {
    id: 'IX-3', title: 'IX-3. Gastric Lesions (위염) - Aspirin',
    titleEn: 'Gastric Lesions', titleKr: '위염',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Aspirin',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 위 손상길이, 위 손상면적',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "2-day", "1-day", "1-day"], page: 51,
  },
  {
    id: 'IX-4', title: 'IX-4. Gastric Lesions (위염 (예방)) - HCl-EtOH',
    titleEn: '', titleKr: '예방',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'HCl-EtOH',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '일반증상, 위 손상길이 측정, 사진촬영, 위 손상 억제율',
    positiveControl: '스티렌, Omeprazole',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-day", "1-week", "1-week"], page: 52,
  },
  {
    id: 'IX-5', title: 'IX-5. Gastric Lesions (위염 (치료)) - HCl-EtOH',
    titleEn: '', titleKr: '치료',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'HCl-EtOH',
    durationWeeks: 9, reportWeeks: 4,
    evalItemsRaw: '일반증상, 위 손상길이 측정, 사진촬영, 위 손상 억제율',
    positiveControl: '스티렌, Omeprazole',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "3-day", "2-week"], page: 53,
  },
  {
    id: 'IX-6', title: 'IX-6. Gastric Lesions (위염 (치료)) - 에탄올',
    titleEn: '', titleKr: '치료',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: '70 % 에탄올',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 위 손상길이 측정, 사진촬영',
    positiveControl: '스티렌',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-hour", "2-day", "5-day"], page: 54,
  },
  {
    id: 'IX-7', title: 'IX-7. Gastrointestinal Transport (장내 수송능)',
    titleEn: 'Gastrointestinal Transport', titleKr: '장내 수송능',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: '',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '운반확인 물질을 투여하고 30 분 경과 후 부검하여 운반확인물질 이동 거리를 백분율로 계산',
    positiveControl: 'Morphine-HCl',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "3-day", "1-day"], page: 55,
  },
  {
    id: 'IX-8', title: 'IX-8. Hangover (숙취해소)',
    titleEn: 'Hangover', titleKr: '숙취해소',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Ethanol',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '에탄올, 아세트 알데히드',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-week"], page: 56,
  },
  {
    id: 'IX-9', title: 'IX-9. HPD & Gastric Activity',
    titleEn: '', titleKr: '',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["Beagle dog"], speciesRaw: 'Beagle dog (Male, 10-12 kg 내외)',
    sex: 'male', ageWeeks: 0,
    inductionMethod: 'HPD 모델 제작',
    durationWeeks: 12, reportWeeks: 4,
    evalItemsRaw: '위액, pH, 총산도',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["2-week", "4-week", "1-week", "1-week"], page: 57,
  },
  {
    id: 'IX-10', title: 'IX-10. Improvement of Digestive Function',
    titleEn: '', titleKr: '',
    categoryCode: 'IX' as CategoryCode, category: '소화기 질환',
    species: ["C57BL/6 mouse"], speciesRaw: '노령쥐 (12 개월령, C57BL/6N, male)',
    sex: 'male', ageWeeks: 0,
    inductionMethod: '',
    durationWeeks: 15, reportWeeks: 4,
    evalItemsRaw: '위 운동성 측정, Gastrin, 소화 효소 활성도 측정',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "4-week", "1-day", "4-week"], page: 58,
  },
  {
    id: 'X-1', title: 'X-1. Glut 4 Expression on Differentiated L6',
    titleEn: '', titleKr: '',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["L6 cell"], speciesRaw: 'L6 cell',
    sex: '', ageWeeks: 0,
    inductionMethod: '',
    durationWeeks: 8, reportWeeks: 4,
    evalItemsRaw: 'Glut4 측정 (RT-PCR)',
    positiveControl: '인슐린',
    isInVitro: true, cellLine: 'L6 cell', cultureCondition: '배양 시 10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-week"], page: 59,
  },
  {
    id: 'X-2', title: 'X-2. Hyperlipidemia (고지혈증) - Rat',
    titleEn: 'Hyperlipidemia', titleKr: '고지혈증',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'AIN-76 + 1 % cholesterol + 0.5 % cholic acid',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '체중, 사료섭취량, 혈액생화학검사, 지방량 측정',
    positiveControl: 'Metformin hydrochloride',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "1-week", "4-week"], page: 60,
  },
  {
    id: 'X-3', title: 'X-3. Hyperlipidemia (고지혈증) - Mouse',
    titleEn: 'Hyperlipidemia', titleKr: '고지혈증',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'Triton WR-1339 300 mg/10 mL/kg',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '체중, 혈액생화학 (LDL, HDL, CHO, TG, AST, ALT, AI)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week"], page: 61,
  },
  {
    id: 'X-4', title: 'X-4. Obesity (비만) - DIO',
    titleEn: 'Obesity', titleKr: '비만',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice (male, 3-week)',
    sex: 'male', ageWeeks: 3,
    inductionMethod: 'Diet induced obesity (DIO)모델, 60 % 고지방식이 섭취',
    durationWeeks: 19, reportWeeks: 4,
    evalItemsRaw: '복부 지방량 측정, 혈액생화학검사, hepatic TG, hepatic TCHO, 사료섭취량, 음수 섭취량',
    positiveControl: '제니칼',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "8-week", "2-week", "4-week"], page: 62,
  },
  {
    id: 'X-5', title: 'X-5. OGTT (당부하검사) - db/db',
    titleEn: 'OGTT', titleKr: '당부하검사',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["db/db mouse"], speciesRaw: 'db/db mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'db/db mice',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '체중, 혈당',
    positiveControl: 'Metformin hydrochloride',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "3-day", "1-day"], page: 63,
  },
  {
    id: 'X-6', title: 'X-6. OGTT (당부하검사) - ICR',
    titleEn: 'OGTT', titleKr: '당부하검사',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["ICR mouse"], speciesRaw: 'ICR mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'Glucose',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '체중, 혈당',
    positiveControl: 'Metformin hydrochloride',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "3-day", "1-day"], page: 64,
  },
  {
    id: 'X-7', title: 'X-7. Type 1 DM (제 1형 당뇨)',
    titleEn: '', titleKr: '',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Streptozotocin (STZ)',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '체중, 사료섭취량, 음수섭취량, 혈당, 혈액생화학적 검사',
    positiveControl: 'Metformin hydrochloride',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "4-day", "4-day"], page: 65,
  },
  {
    id: 'X-8', title: 'X-8. Type 2 DM (제 2형 당뇨)',
    titleEn: '', titleKr: '',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["db/db mouse"], speciesRaw: 'db/db mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'db/db mice',
    durationWeeks: 10, reportWeeks: 4,
    evalItemsRaw: '체중, 혈당, OGTT, Insulin 측정, 사료섭취량, 음수섭취량, 혈액생화학적 검사, 조직병리 (H&E)',
    positiveControl: 'Metformin hydrochloride',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "1-day", "1-week"], page: 66,
  },
  {
    id: 'X-9', title: 'X-9. 통풍 - Rat',
    titleEn: '', titleKr: '',
    categoryCode: 'X' as CategoryCode, category: '대사성 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'Potassium oxonate 투여(IP)',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '체중, Uric acid, Xanthine oxidase 저해 활성 측정',
    positiveControl: 'Febuxostat, Allopurinol',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "1-week", "4-week"], page: 67,
  },
  {
    id: 'XI-1', title: 'XI-1. Menopause (갱년기) - Hot Flashes Test',
    titleEn: 'Menopause', titleKr: '갱년기',
    categoryCode: 'XI' as CategoryCode, category: '내분비 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (female, 12-week)',
    sex: 'male', ageWeeks: 12,
    inductionMethod: 'Oophorectomy (난소적출)',
    durationWeeks: 15, reportWeeks: 4,
    evalItemsRaw: '꼬리온도 측정 (2 회/주), 혈액생화학',
    positiveControl: 'E2 (estradiol)',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "8-week", "1-week"], page: 68,
  },
  {
    id: 'XI-2', title: 'XI-2. Menopause (갱년기)',
    titleEn: 'Menopause', titleKr: '갱년기',
    categoryCode: 'XI' as CategoryCode, category: '내분비 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (female, 12-week)',
    sex: 'male', ageWeeks: 12,
    inductionMethod: 'Cisplatin 1 회/일, 총 10 회, 2 mg/kg/day',
    durationWeeks: 17, reportWeeks: 4,
    evalItemsRaw: 'E2 (estradiol), AMH, FSH 측정 (ELISA), 조직병리학적 검사',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "10-day", "1-day", "8-week"], page: 69,
  },
  {
    id: 'XII-1', title: 'XII-1. Atopic Dermatitis (아토피성 피부염)',
    titleEn: 'Atopic Dermatitis', titleKr: '아토피성 피부염',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["NC/Nga mouse"], speciesRaw: 'NC/Nga mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'Dinitrochlorobenzene (DNCB)',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '체중, IgE, IL-4, IL-13, IFN-g, 사진촬영, 관능평가, 스크래치측정, 조직병리 (피부두께, 상피두께, 침윤염증세포 수, 비만세포 수, Collagen fiber)',
    positiveControl: 'Dexamethasone',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "4-week", "4-week"], page: 70,
  },
  {
    id: 'XII-2', title: 'XII-2. Anti Wrinkle Effect, in vitro (주름개선)',
    titleEn: 'in vitro', titleKr: '주름개선',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["CCD986sk cell"], speciesRaw: 'CCD986sk cells',
    sex: '', ageWeeks: 0,
    inductionMethod: '',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '세포독성, 콜라겐 측정',
    positiveControl: 'TGF-b1',
    isInVitro: true, cellLine: 'CCD986sk cells', cultureCondition: '10 % FBS in DMEM',
    scheduleDurations: ["1-week", "1-week", "1-week"], page: 71,
  },
  {
    id: 'XII-3', title: 'XII-3. Anti Wrinkle Effect, in vivo (주름개선)',
    titleEn: 'in vivo', titleKr: '주름개선',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["SKH-1 hairless mouse"], speciesRaw: 'Hairless mice (female, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: '0.3 mg/0.1 mL/head Calcitriol 1 회/일, 5 회/주 도포',
    durationWeeks: 21, reportWeeks: 4,
    evalItemsRaw: 'Replica, 조직병리 (표피두께, 미세주름 수, 진피두께)',
    positiveControl: 'Restylene, Amalian SF 24 Advanced,',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "8-week", "4-week"], page: 72,
  },
  {
    id: 'XII-4', title: 'XII-4. Burn Wound (화상)',
    titleEn: 'Burn Wound', titleKr: '화상',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: '80 ºC 인두기로 화상 유발',
    durationWeeks: 8, reportWeeks: 4,
    evalItemsRaw: '사진촬영, 화상면적, 조직병리 (상피의 결손 부위 길이, 농포깊이, 침윤세포 수, 변성-육아조직 면적, 상피 재생율 상피 두께, 콜라겐 섬유)',
    positiveControl: 'Vaselin',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "2-week", "1-week"], page: 73,
  },
  {
    id: 'XII-5', title: 'XII-5. Wound (창상)',
    titleEn: 'Wound', titleKr: '창상',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: '8 mm biopsy punch로 창상 유발',
    durationWeeks: 8, reportWeeks: 4,
    evalItemsRaw: '사진촬영, 창상면적, 조직병리',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "2-week", "1-week"], page: 74,
  },
  {
    id: 'XII-6', title: 'XII-6. Hair Growth (발모)',
    titleEn: 'Hair Growth', titleKr: '발모',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: '제모',
    durationWeeks: 12, reportWeeks: 4,
    evalItemsRaw: '체중, 발모 면적(%), 발모 부위 조직병리 (모낭 주기별 분석, 피부두께 측정)',
    positiveControl: '미녹시딜',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "3-week", "4-week"], page: 75,
  },
  {
    id: 'XII-7', title: 'XII-7. Hair Loss (탈모)',
    titleEn: 'Hair Loss', titleKr: '탈모',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: '제모, Testosterone Propionate (TP) 투여',
    durationWeeks: 17, reportWeeks: 4,
    evalItemsRaw: '체중, 발모 면적(%), 발모 부위 조직병리 (모낭 주기별 분석, 피부두께 측정)',
    positiveControl: 'Minoxidil',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "7-week", "4-week"], page: 76,
  },
  {
    id: 'XII-8', title: 'XII-8. Skin Infection (피부감염)',
    titleEn: 'Skin Infection', titleKr: '피부감염',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["Guinea pig"], speciesRaw: 'Guinea Pig (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: '진균 감염',
    durationWeeks: 9, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 사진촬영, 피부변화 (Score)',
    positiveControl: '라미실 크림',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "3-week", "1-day"], page: 77,
  },
  {
    id: 'XII-9', title: 'XII-9. Whitening, in vitro (미백)',
    titleEn: 'in vitro', titleKr: '미백',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["B16F1 cell"], speciesRaw: 'B16F1 (murine melanoma cell)',
    sex: '', ageWeeks: 0,
    inductionMethod: '',
    durationWeeks: 8, reportWeeks: 4,
    evalItemsRaw: '세포독성, 멜라닌 함량 측정',
    positiveControl: 'Arbutin',
    isInVitro: true, cellLine: 'B16F1 (murine melanoma cell)', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "1-week", "2-week"], page: 78,
  },
  {
    id: 'XII-10', title: 'XII-10. Photoaging (광노화) – UVB',
    titleEn: 'Photoaging', titleKr: '광노화',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["SKH-1 hairless mouse"], speciesRaw: 'Hairless mice (female, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'Ultraviolet-B (UVB) radiation',
    durationWeeks: 21, reportWeeks: 4,
    evalItemsRaw: '체중, 피부 수분 함량 (skin hydrations; SH), 피부 탄력도 (skin elasticity; SE) 수분 손실량 (transepidemal water loss; TEWL), 피부 주름 (replica), 조직병리 (피부두께, 피부 주름 개수, 침윤염증세포 수)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "6-week", "4-week", "4-week"], page: 79,
  },
  {
    id: 'XII-11', title: 'XII-11. Skin atrophy (피부위축증) – Psoriasis',
    titleEn: 'Skin atrophy', titleKr: '피부위축증',
    categoryCode: 'XII' as CategoryCode, category: '피부 질환',
    species: ["SKH-1 hairless mouse"], speciesRaw: 'Hairless mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'Imiquimod (건선유발), clobetasol propionate (스테로이드 처리)',
    durationWeeks: 17, reportWeeks: 4,
    evalItemsRaw: '체중, 관능평가, 피부두께측정, 사진촬영, 조직병리 (전체 피부 두께, 표피 두께, 주름 수, 염증세포 수, collagen 함량 변화)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "4-week", "4-week"], page: 80,
  },
  {
    id: 'XIII-1', title: 'XIII-1. Breast Cancer (유방암) - MCF-7',
    titleEn: 'Breast Cancer', titleKr: '유방암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (female, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'MCF-7 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Adriamycin (Doxorubicin)',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 81,
  },
  {
    id: 'XIII-2', title: 'XIII-2. Breast Cancer (유방암) - MDA-MB-231',
    titleEn: 'Breast Cancer', titleKr: '유방암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (female, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'MDA-MB-231 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Paclitaxel',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 82,
  },
  {
    id: 'XIII-3', title: 'XIII-3. Colon Cancer (대장암)',
    titleEn: 'Colon Cancer', titleKr: '대장암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'Colo 205 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Adriamycin (Doxorubicin)',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 83,
  },
  {
    id: 'XIII-4', title: 'XIII-4. Gastric Cancer (위암)',
    titleEn: 'Gastric Cancer', titleKr: '위암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'MKN-45 cell, xenograft',
    durationWeeks: None, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Adriamycin (Doxorubicin)',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 84,
  },
  {
    id: 'XIII-5', title: 'XIII-5. Hepatocellular Carcinoma (간암)',
    titleEn: 'Hepatocellular Carcinoma', titleKr: '간암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'Huh7 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Sorafenib',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 85,
  },
  {
    id: 'XIII-6', title: 'XIII-6. Lung Cancer (폐암)',
    titleEn: 'Lung Cancer', titleKr: '폐암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'A549 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Adriamycin (Doxorubicin)',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 86,
  },
  {
    id: 'XIII-7', title: 'XIII-7. Nasopharyngeal Cancer (비인두암)',
    titleEn: 'Nasopharyngeal Cancer', titleKr: '비인두암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'KB cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Paclitaxel',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 87,
  },
  {
    id: 'XIII-8', title: 'XIII-8. Prostate Cancer (전립선암)',
    titleEn: 'Prostate Cancer', titleKr: '전립선암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'DU145 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Taxotere',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 88,
  },
  {
    id: 'XIII-9', title: 'XIII-9. Pancreatic Cancer (췌장암)',
    titleEn: 'Pancreatic Cancer', titleKr: '췌장암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'PANC-1 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Paclitaxel',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 89,
  },
  {
    id: 'XIII-10', title: 'XIII-10. Breast Cancer (유방암)',
    titleEn: 'Breast Cancer', titleKr: '유방암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["mouse"], speciesRaw: 'NOD SCID mice (female, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'BT-474 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 90,
  },
  {
    id: 'XIII-11', title: 'XIII-11. Brain Cancer (뇌암)',
    titleEn: 'Brain Cancer', titleKr: '뇌암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["mouse"], speciesRaw: 'NOG or NOD SCID mice (female, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'U87-MG cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 91,
  },
  {
    id: 'XIII-12', title: 'XIII-12. Gallbladder Cancer (담낭암)',
    titleEn: 'Gallbladder Cancer', titleKr: '담낭암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["mouse"], speciesRaw: 'NOG or NOD SCID mice (female, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'JHH-5 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 92,
  },
  {
    id: 'XIII-13', title: 'XIII-13. Laryngeal Cancer (후두암)',
    titleEn: 'Laryngeal Cancer', titleKr: '후두암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["mouse"], speciesRaw: 'NOG mice (female, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'HEp-2 cell, xenograft',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "2-week", "4-week"], page: 93,
  },
  {
    id: 'XIII-14', title: 'XIII-14. Bile duct carcinoma (담도암)',
    titleEn: 'Bile duct carcinoma', titleKr: '담도암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'HuCCT1 cell, xenograft',
    durationWeeks: 15, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Cobimetinib',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "4-week", "4-week"], page: 94,
  },
  {
    id: 'XIII-15', title: 'XIII-15. Biliary tract cancer (담관암)',
    titleEn: 'Biliary tract cancer', titleKr: '담관암',
    categoryCode: 'XIII' as CategoryCode, category: '항암',
    species: ["BALB/c nude mouse"], speciesRaw: 'BALB/c nude mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'SNU-869 cell, xenograft',
    durationWeeks: 12, reportWeeks: 4,
    evalItemsRaw: '종양부피, 종양무게, 사진촬영',
    positiveControl: 'Cobimetinib',
    isInVitro: false, cellLine: '', cultureCondition: '10 % FBS in RPMI 1640',
    scheduleDurations: ["1-week", "2-week", "1-week", "1-week", "4-week"], page: 95,
  },
  {
    id: 'XIV-1', title: 'XIV-1. Antibacterial Effect (항균) - MIC',
    titleEn: 'Antibacterial Effect', titleKr: '항균',
    categoryCode: 'XIV' as CategoryCode, category: '항균',
    species: ["in vitro (bacteria)"], speciesRaw: 'Staphylococcus epidermidis, Corynebacterium glutamicum,',
    sex: '', ageWeeks: 0,
    inductionMethod: '균 배양',
    durationWeeks: 11, reportWeeks: 4,
    evalItemsRaw: 'Antibacterial susceptibility test (MIC)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "2-week", "4-week"], page: 96,
  },
  {
    id: 'XIV-2', title: 'XIV-2. Anti Fungal Effect (항진균효과)',
    titleEn: 'Anti Fungal Effect', titleKr: '항진균효과',
    categoryCode: 'XIV' as CategoryCode, category: '항균',
    species: ["in vitro"], speciesRaw: 'ICR mice (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'Candida albican ATCC 36082',
    durationWeeks: 9, reportWeeks: 4,
    evalItemsRaw: '생존율, 체중',
    positiveControl: 'Fluconazole',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-week", "3-week"], page: 97,
  },
  {
    id: 'XIV-3', title: 'XIV-3. Anti Fungal Effect (항진균효과)',
    titleEn: 'Anti Fungal Effect', titleKr: '항진균효과',
    categoryCode: 'XIV' as CategoryCode, category: '항균',
    species: ["in vitro"], speciesRaw: 'ICR mice (female, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'Aspergillus fumigates ATCC16424',
    durationWeeks: 8, reportWeeks: 4,
    evalItemsRaw: '체중, 생존율',
    positiveControl: 'Fluconazole, Amphotericin B, Voriconazole',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "3-day", "5-day", "2-week"], page: 98,
  },
  {
    id: 'XIV-4', title: 'XIV-4. Anti Onychomycosis Effect (항진균)',
    titleEn: 'Anti Onychomycosis Effect', titleKr: '항진균',
    categoryCode: 'XIV' as CategoryCode, category: '항균',
    species: ["in vitro"], speciesRaw: 'Guinea pig (male, 5-week)',
    sex: 'male', ageWeeks: 5,
    inductionMethod: 'Trichophyton mentagrophytes, ATCC 32457',
    durationWeeks: 18, reportWeeks: 4,
    evalItemsRaw: '체중, 임상증상, CFU 분석 (감염 발톱 내 균주의 집락형성능 분석), 조직병리 (염증세포 수, 침습 진균 수)',
    positiveControl: 'Efinaconazole',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "2-week", "4-week", "4-week", "4-week"], page: 99,
  },
  {
    id: 'XV-1', title: 'XV-1. Alcoholic Fatty Liver (알코올성 지방간)',
    titleEn: 'Alcoholic Fatty Liver', titleKr: '알코올성 지방간',
    categoryCode: 'XV' as CategoryCode, category: '간질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6J mice (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: 'Alcoholic Diet',
    durationWeeks: 17, reportWeeks: 4,
    evalItemsRaw: '간 조직 내 TG, TC, TNF-a, 측정, 혈액생화학적 변화, 조직병리 (지방간 병변 비율, 평균 간세포 직경)',
    positiveControl: 'Silymarin',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "6-week", "2-week", "4-week"], page: 100,
  },
  {
    id: 'XV-2', title: 'XV-2. Liver Cirrhosis (간경화) - BDL',
    titleEn: 'Liver Cirrhosis', titleKr: '간경화',
    categoryCode: 'XV' as CategoryCode, category: '간질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 9-week)',
    sex: 'male', ageWeeks: 9,
    inductionMethod: 'Bile Duct Ligation (BDL) 수술',
    durationWeeks: 15, reportWeeks: 4,
    evalItemsRaw: '체중, 혈액생화학적 변화, 조직병리 (간 실질 중 변성 비율, 침윤세포 수, 담관 수 Collagen fiber가 차지하는 영역 비율), ELISA, 장기무게, RT-PCR',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "2-week", "4-week", "4-week"], page: 101,
  },
  {
    id: 'XV-3', title: 'XV-3. Liver Fibrosis (간섬유화) - DMN',
    titleEn: 'Liver Fibrosis', titleKr: '간섬유화',
    categoryCode: 'XV' as CategoryCode, category: '간질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Dimethylnitrosamine (DMN)',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '일반증상, 체중변화, 장기 무게, 혈액생화학적 검사, 조직병리 (간 실질 중 변성 비율, 침윤세포 수, 담관 수, Collagen fiber가 차지하는 영역 비율)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "3-week", "2-week", "4-week"], page: 102,
  },
  {
    id: 'XV-4', title: 'XV-4. Liver Injury (간손상)',
    titleEn: 'Liver Injury', titleKr: '간손상',
    categoryCode: 'XV' as CategoryCode, category: '간질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rats (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'D-galactosamine',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '혈액생화학적 변화, 장기무게, 간조직 항산화능',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "2-week", "4-week", "2-week"], page: 103,
  },
  {
    id: 'XV-5', title: 'XV-5. NAFLD (비알콜성 지방간) - MCD diet',
    titleEn: 'NAFLD', titleKr: '비알콜성 지방간',
    categoryCode: 'XV' as CategoryCode, category: '간질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 4-week)',
    sex: 'male', ageWeeks: 4,
    inductionMethod: 'Choline Def.&Iron Suppl. L-AA without L-Methionine (MCD diet)',
    durationWeeks: 17, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 혈액생화학, 조직병리 (지방간 병변 비율), 간 조직 내 TG, TCHO, 간 무게 측정',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "4-week", "4-week", "4-week"], page: 104,
  },
  {
    id: 'XV-6', title: 'XV-6. Hepatic IRI(간허헐)',
    titleEn: 'Hepatic IRI', titleKr: '간허헐',
    categoryCode: 'XV' as CategoryCode, category: '간질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rats (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: 'Liver의 left lateral lobe와 median lobe에 간동맥과 간문맥 차단',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: '혈액생화학적 변화, 장기무게, 간 조직병리, 간조직 TNF-a',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "4-week", "2-week"], page: 105,
  },
  {
    id: 'XVI-1', title: 'XVI-1. Angiogenesis (혈관신생) - CPA',
    titleEn: 'Angiogenesis', titleKr: '혈관신생',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice (male, 9-week)',
    sex: 'male', ageWeeks: 9,
    inductionMethod: 'Corneal Pocket Assay (CPA)',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '혈관생성 및 구조적 특징 이미지분석',
    positiveControl: 'VEGF',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-week", "1-week"], page: 106,
  },
  {
    id: 'XVI-2', title: 'XVI-2. Bone Growth (골 성장)',
    titleEn: 'Bone Growth', titleKr: '골 성장',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 mice 8 weeks male/female',
    sex: 'male', ageWeeks: 0,
    inductionMethod: '',
    durationWeeks: 9, reportWeeks: 4,
    evalItemsRaw: '이미지분석',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "3-week", "2-day", "1-week"], page: 107,
  },
  {
    id: 'XVI-3', title: 'XVI-3. Intestinal Adhesions (장유착)',
    titleEn: 'Intestinal Adhesions', titleKr: '장유착',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: '대장과 그에 맞닿은 내측 복벽을 찰과상을 내어 맞닿게 하여',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 장유착정도 및 세기, 사진촬영, 조직병리',
    positiveControl: 'GS05, 가딕스-SG',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "2-week", "1-day"], page: 108,
  },
  {
    id: 'XVI-4', title: 'XVI-4. Sepsis (패혈증) - LPS',
    titleEn: 'Sepsis', titleKr: '패혈증',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'LPS',
    durationWeeks: 6, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, 생존율',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-week"], page: 109,
  },
  {
    id: 'XVI-5', title: 'XVI-5. Sepsis (패혈증) - CLP',
    titleEn: 'Sepsis', titleKr: '패혈증',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["C57BL/6 mouse"], speciesRaw: 'C57BL/6 (male, 8-week)',
    sex: 'male', ageWeeks: 8,
    inductionMethod: 'CLP (cecal ligation and puncture)',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: '체중, 체온, 일반증상, 생존율',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "1-week"], page: 110,
  },
  {
    id: 'XVI-6', title: 'XVI-6. Periodontitis (치주염) - 대구치 결찰',
    titleEn: 'Periodontitis', titleKr: '치주염',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["Wistar rat"], speciesRaw: 'Wistar rat (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: '제 1 대구치 결찰',
    durationWeeks: 9, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, myeloperoxidase (MPO) 측정, Micro CT 기 타 질 환 조직병리 (H&E, 염증세포 침윤, 염증세포 수, 상피화, Propria 층 내 혈관확장)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-week", "3-week", "1-day"], page: 111,
  },
  {
    id: 'XVI-7', title: 'XVI-7. Biodegradability Test (생분해성)',
    titleEn: 'Biodegradability Test', titleKr: '생분해성',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["SD rat"], speciesRaw: 'Sprague Dawley rat (male, 6-week)',
    sex: 'male', ageWeeks: 6,
    inductionMethod: '물질 투여 (피내, 피하)',
    durationWeeks: 61, reportWeeks: 4,
    evalItemsRaw: '체중, 일반증상, MRI, 조직병리(H&E)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-week", "1-day", "52-week", "4-week"], page: 112,
  },
  {
    id: 'XVI-8', title: 'XVI-8. 토끼 부비동염 유발',
    titleEn: '', titleKr: '',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["NZW rabbit"], speciesRaw: 'Newzealand white rabbit, 9 weeks female',
    sex: 'male', ageWeeks: 0,
    inductionMethod: '',
    durationWeeks: 13, reportWeeks: 4,
    evalItemsRaw: 'Micro-CT 이미지분석, 조직병리 검사',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "2-week", "2-day", "8-week"], page: 113,
  },
  {
    id: 'XVI-9', title: 'XVI-9. 수면유도 모델 (불면증 효력)',
    titleEn: '', titleKr: '불면증 효력',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["ICR mouse"], speciesRaw: 'ICR mice 7 weeks male',
    sex: 'male', ageWeeks: 0,
    inductionMethod: '',
    durationWeeks: 9, reportWeeks: 4,
    evalItemsRaw: '수면유도시간, 수면시간 측정, 혈청 내 멜라토닌 및 세로토닌 측정, 뇌조직 병리학적 검사',
    positiveControl: 'L-tryptophan',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "1-day", "1-day", "4-week"], page: 114,
  },
  {
    id: 'XVI-10', title: 'XVI-10. Muscle Improvement (근력개선)',
    titleEn: 'Muscle Improvement', titleKr: '근력개선',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["C57BL/6 mouse"], speciesRaw: '노령쥐 (12 개월령, C57BL/6N, male)',
    sex: 'male', ageWeeks: 0,
    inductionMethod: '',
    durationWeeks: 21, reportWeeks: 4,
    evalItemsRaw: '행동실험, micro-CT, 혈액생화학적검사 (CRE), 조직병리학적 검사 기 타 질 환',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "8-week", "8-week"], page: 115,
  },
  {
    id: 'XVI-11', title: 'XVI-11. Medical device equivalence Test',
    titleEn: '', titleKr: '',
    categoryCode: 'XVI' as CategoryCode, category: '기타 질환',
    species: ["Yucatan mini pig"], speciesRaw: 'Yucatan Mini Pig (Female, 10-20 kg 내외)',
    sex: 'male', ageWeeks: 0,
    inductionMethod: '장기(간, 신장, 대퇴근육, 피부)내 probe (≒cannula) 삽입 후 전기자극',
    durationWeeks: 10, reportWeeks: 4,
    evalItemsRaw: '열화상면적, 최고온도, 기저온도 복귀시간, 조직병리(H&E)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["2-week", "3-day", "2-week", "4-week"], page: 116,
  },
  {
    id: 'ADME Center', title: 'ADME Center',
    titleEn: '', titleKr: '',
    categoryCode: 'ETC' as CategoryCode, category: '',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: '',
    durationWeeks: 14, reportWeeks: 4,
    evalItemsRaw: '생체시료 분석법 밸리데이션 가이드라인 (안내서-0024-01, MFDS, 2013년 12월)',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "2-week", "7-week", "7-day", "3-day"], page: 123,
  },
  {
    id: 'ADME Center', title: 'ADME Center',
    titleEn: '', titleKr: '',
    categoryCode: 'ETC' as CategoryCode, category: '',
    species: ["SD rat"], speciesRaw: 'Sprague-Dawley (SD) rat (male, 7-week)',
    sex: 'male', ageWeeks: 7,
    inductionMethod: '',
    durationWeeks: 7, reportWeeks: 4,
    evalItemsRaw: 'AUClast (ng*hr/mL), Cmax (ng/mL), t1/2 (hr), bioavailability',
    positiveControl: '',
    isInVitro: false, cellLine: '', cultureCondition: '',
    scheduleDurations: ["1-week", "2-week", "1-week", "1-week", "3-day"], page: 124,
  },
];


export function getModelsByCategory(code: CategoryCode): StudyModel[] { return STUDY_MODELS.filter(m => m.categoryCode === code); }
export function getModelsBySpecies(species: string): StudyModel[] { return STUDY_MODELS.filter(m => m.species.some(s => s.toLowerCase().includes(species.toLowerCase()))); }
export function getModelById(id: string): StudyModel | undefined { return STUDY_MODELS.find(m => m.id === id); }
export function searchModels(keyword: string): StudyModel[] {
  const kw = keyword.toLowerCase();
  return STUDY_MODELS.filter(m => m.title.toLowerCase().includes(kw) || m.evalItemsRaw.toLowerCase().includes(kw) || m.inductionMethod.toLowerCase().includes(kw) || m.titleEn.toLowerCase().includes(kw) || m.titleKr.includes(keyword));
}
export function getInVivoModels(): StudyModel[] { return STUDY_MODELS.filter(m => !m.isInVitro); }
export function getInVitroModels(): StudyModel[] { return STUDY_MODELS.filter(m => m.isInVitro); }
